---
title: "GSE236575 RNA-seq × ATAC-seq Integration"
subtitle: "TRAP-seq HFD vs CHD — targeted gene analysis, ATAC peak annotation, motif stratification"
author: "Dave Bridges"
date: "2026-05-12"
editor: source
format:
  html:
    toc: true
    toc-location: right
    keep-md: true
    code-fold: true
    code-summary: "Show code"
    fig-path: "figures/rnaseq/"
  gfm:
    html-math-method: webtex
theme: journal
execute:
  echo: true
  warning: false
knitr:
  opts_chunk:
    fig-path: "figures/rnaseq/"
    dev: ["png", "pdf"]
    dpi: 300
    dev.args:
      png:
        type: "cairo-png"
      pdf:
        family: "sans"
---


::: {.cell}

:::


## Dataset overview

### RNA-seq data source

The matched RNA-seq data are from **GSE236578 [TRAP]**, a sub-series of the
super-series GSE236580 ("Adipose tissue retains an epigenetic memory of obesity
after weight loss"; PMID 39558077).  The same AdipER-Cre/NuTRAP mice and eWAT
adipocyte preparations were used for both ATAC-seq (GSE236575) and TRAP-seq
(GSE236578).  TRAP-seq captures actively translated transcripts specifically
from adipocytes, avoiding contamination from stromal-vascular cells.

| Sample ID | GSM | SRR | Condition |
|-----------|-----|-----|-----------|
| CHD_1 | GSM7558266 | SRR25152278 | Chow diet |
| CHD_2 | GSM7558271 | SRR25152274 | Chow diet |
| CHD_3 | GSM7558276 | SRR25152266 | Chow diet |
| HFD_1 | GSM7558267 | SRR25152277 | High-fat diet |
| HFD_2 | GSM7558272 | SRR25152273 | High-fat diet |
| HFD_3 | GSM7558277 | SRR25152265 | High-fat diet |

Library: paired-end 150 bp, template switching (Maxima H Minus RT), unstranded.
Alignment: STAR → mm10/GENCODE vM25, unique mappers only.
Quantification: featureCounts, gene_name, unstranded (-s 0).

### Pipeline output files

All files are generated by the `RNASEQ_DESEQ2` Nextflow process.


::: {.cell}

```{.r .cell-code}
deseq_file    <- "results/rnaseq/deseq2/rnaseq_deseq2_results.txt"
targeted_file <- "results/rnaseq/deseq2/rnaseq_targeted_genes.tsv"
norm_file     <- "results/rnaseq/deseq2/rnaseq_normalized_counts.txt"
atac_deseq    <- "results/deseq2/deseq2_results.txt"
```
:::


---

## 1. DESeq2 differential expression — global summary


::: {.cell}

```{.r .cell-code}
library(readr)
library(dplyr)

deseq <- read_tsv(deseq_file, show_col_types=FALSE) |>
  rename(gene = 1)   # col 1 is the row-names field written by write.table; rownames_to_column() inserts integers on tibbles

cat("Total genes tested:", nrow(deseq), "\n")
```

::: {.cell-output .cell-output-stdout}

```
Total genes tested: 22901 
```


:::

```{.r .cell-code}
cat("HFD-up   (padj<0.05, LFC>0.585):",
    sum(!is.na(deseq$padj) & deseq$padj < 0.05 & deseq$log2FoldChange > 0.585), "\n")
```

::: {.cell-output .cell-output-stdout}

```
HFD-up   (padj<0.05, LFC>0.585): 4466 
```


:::

```{.r .cell-code}
cat("HFD-down (padj<0.05, LFC< -0.585):",
    sum(!is.na(deseq$padj) & deseq$padj < 0.05 & deseq$log2FoldChange < -0.585), "\n")
```

::: {.cell-output .cell-output-stdout}

```
HFD-down (padj<0.05, LFC< -0.585): 0 
```


:::
:::



::: {.cell}

```{.r .cell-code}
library(ggrepel)
library(ggplot2)

tg_genes <- c("Fos","Jun","Junb","Jund","Fosl1","Fosl2","Batf","Batf3","Atf3","Atf4","Ddit3",
              "Vdr","Ncoa1","Ncoa2","Ncoa3","Med1",
              "Hsd11b1","Nr3c1","Fkbp5","Sgk1","Tsc22d3")

deseq_plot <- deseq |>
  mutate(
    sig = !is.na(padj) & padj < 0.05 & abs(log2FoldChange) > 0.585,
    label = ifelse(gene %in% tg_genes, gene, NA_character_)
  )

ggplot(deseq_plot, aes(log2FoldChange, -log10(pvalue))) +
  geom_point(aes(color=sig), alpha=0.4, size=0.7) +
  scale_color_manual(values=c("FALSE"="grey70","TRUE"="#d62728"), guide="none") +
  geom_text_repel(aes(label=label), size=3, max.overlaps=40,
                  segment.color="grey60") +
  geom_hline(yintercept=-log10(0.05), lty=2, color="grey50") +
  geom_vline(xintercept=c(-0.585, 0.585), lty=2, color="grey50") +
  labs(x="log2FC (HFD / CHD)", y="-log10(p-value)",
       title="TRAP-seq: HFD vs CHD differential expression",
       subtitle="Red = FDR<0.05, |LFC|>0.585; labelled genes = targeted candidates") +
  theme_classic(base_size=13)
```

::: {.cell-output-display}
![](figures/rnaseq/volcano-global-1.png){width=2700}
:::
:::


---

## 2. Targeted gene analysis

### Load and display results


::: {.cell}

```{.r .cell-code}
tg <- read_tsv(targeted_file, show_col_types=FALSE)

# Format for display
tg_display <- tg |>
  mutate(
    across(c(log2FoldChange, lfcSE, bayes_CrI_lo, bayes_CrI_hi), ~round(., 3)),
    across(c(pvalue, padj), ~signif(., 3)),
    across(c(bayes_P_HFD_gt_CHD, bayes_ER), ~round(., 3)),
    across(c(mean_norm_CHD, mean_norm_HFD), ~round(., 1))
  ) |>
  dplyr::select(category, gene, log2FoldChange, lfcSE, padj, pvalue,
         mean_norm_CHD, mean_norm_HFD, detected,
         bayes_P_HFD_gt_CHD, bayes_ER, bayes_CrI_lo, bayes_CrI_hi)

knitr::kable(tg_display,
  caption="Targeted gene-level TRAP-seq results (HFD vs CHD). Bayes stats use Normal(0,1) prior on log2FC (analytical conjugate update).",
  digits=c(0,0,3,3,3,3,1,1,0,3,2,3,3))
```

::: {.cell-output-display}


Table: Targeted gene-level TRAP-seq results (HFD vs CHD). Bayes stats use Normal(0,1) prior on log2FC (analytical conjugate update).

|category       |gene    | log2FoldChange| lfcSE|  padj| pvalue| mean_norm_CHD| mean_norm_HFD|detected | bayes_P_HFD_gt_CHD| bayes_ER| bayes_CrI_lo| bayes_CrI_hi|
|:--------------|:-------|--------------:|-----:|-----:|------:|-------------:|-------------:|:--------|------------------:|--------:|------------:|------------:|
|AP-1           |Atf3    |          1.931| 0.715| 0.053|  0.007|          67.2|         256.4|TRUE     |              0.986|    70.13|        0.137|        2.418|
|AP-1           |Atf4    |         -0.575| 0.403| 0.386|  0.154|        3406.8|        2287.6|TRUE     |              0.093|     0.10|       -1.227|        0.238|
|AP-1           |Batf    |          2.167| 1.420| 0.346|  0.127|           4.5|          20.1|TRUE     |              0.810|     4.27|       -0.883|        2.321|
|AP-1           |Batf3   |         -0.098| 0.660| 0.953|  0.882|         129.7|         121.1|TRUE     |              0.451|     0.82|       -1.148|        1.012|
|AP-1           |Ddit3   |          1.051| 0.429| 0.087|  0.014|         407.1|         843.8|TRUE     |              0.988|    81.05|        0.115|        1.661|
|AP-1           |Fos     |          1.866| 0.642| 0.034|  0.004|          80.8|         294.0|TRUE     |              0.993|   136.55|        0.261|        2.380|
|AP-1           |Fosl1   |             NA|    NA|    NA|     NA|            NA|            NA|FALSE    |                 NA|       NA|           NA|           NA|
|AP-1           |Fosl2   |         -0.112| 0.415| 0.910|  0.788|         945.9|         875.2|TRUE     |              0.402|     0.67|       -0.846|        0.656|
|AP-1           |Jun     |          0.206| 0.437| 0.827|  0.637|         637.0|         735.1|TRUE     |              0.667|     2.00|       -0.612|        0.958|
|AP-1           |Junb    |          1.927| 0.572| 0.012|  0.001|          36.3|         137.4|TRUE     |              0.998|   582.90|        0.480|        2.425|
|AP-1           |Jund    |          0.377| 0.567| 0.740|  0.505|         445.2|         578.8|TRUE     |              0.719|     2.56|       -0.680|        1.252|
|artifact_check |Dmrt1   |             NA|    NA|    NA|     NA|            NA|            NA|FALSE    |                 NA|       NA|           NA|           NA|
|artifact_check |Dmrt2   |         -1.699| 0.774| 0.135|  0.028|        1620.4|         499.5|TRUE     |              0.041|     0.04|       -2.262|        0.137|
|artifact_check |Dmrt3   |             NA|    NA|    NA|     NA|            NA|            NA|FALSE    |                 NA|       NA|           NA|           NA|
|artifact_check |Dmrt4   |             NA|    NA|    NA|     NA|            NA|            NA|FALSE    |                 NA|       NA|           NA|           NA|
|demoted        |Cebpa   |          0.348| 0.759| 0.833|  0.647|        2655.5|        3380.1|TRUE     |              0.643|     1.80|       -0.964|        1.406|
|demoted        |Cebpb   |         -0.503| 0.641| 0.684|  0.433|        1218.0|         860.0|TRUE     |              0.254|     0.34|       -1.414|        0.701|
|demoted        |Cebpd   |          0.909| 0.520| 0.263|  0.080|         167.3|         314.5|TRUE     |              0.940|    15.54|       -0.189|        1.620|
|demoted        |Foxa1   |         -2.635| 2.282|    NA|  0.248|           3.7|           0.6|FALSE    |              0.321|     0.47|       -2.220|        1.371|
|demoted        |Foxa2   |             NA|    NA|    NA|     NA|            NA|            NA|FALSE    |                 NA|       NA|           NA|           NA|
|demoted        |Foxo1   |         -0.060| 0.454| 0.959|  0.895|        1983.4|        1902.8|TRUE     |              0.452|     0.82|       -0.861|        0.761|
|demoted        |Foxo3   |          0.116| 0.313| 0.870|  0.711|         566.1|         613.4|TRUE     |              0.638|     1.76|       -0.480|        0.691|
|demoted        |Klf13   |          0.530| 0.347| 0.345|  0.127|        1193.4|        1723.5|TRUE     |              0.925|    12.42|       -0.169|        1.115|
|demoted        |Prrx1   |          0.991| 0.363| 0.050|  0.006|         499.2|         991.8|TRUE     |              0.995|   195.39|        0.208|        1.544|
|GR_target      |Angptl4 |          1.949| 0.482| 0.002|  0.000|        1978.5|        7638.5|TRUE     |              1.000|  7329.34|        0.730|        2.433|
|GR_target      |Fkbp5   |         -1.292| 0.376| 0.010|  0.001|        1414.6|         578.1|TRUE     |              0.001|     0.00|       -1.822|       -0.443|
|GR_target      |Hsd11b1 |         -0.933| 0.403| 0.110|  0.021|        1719.2|         900.1|TRUE     |              0.016|     0.02|       -1.535|       -0.070|
|GR_target      |Hsd11b2 |          0.914| 1.025| 0.634|  0.372|           7.2|          13.5|TRUE     |              0.733|     2.75|       -0.957|        1.849|
|GR_target      |Lep     |          2.009| 0.612| 0.014|  0.001|       14331.1|       57685.3|TRUE     |              0.997|   388.36|        0.438|        2.485|
|GR_target      |Nr3c1   |         -0.303| 0.449| 0.736|  0.499|        4396.3|        3563.4|TRUE     |              0.269|     0.37|       -1.055|        0.550|
|GR_target      |Pnpla2  |          0.319| 0.727| 0.842|  0.661|        3987.8|        4973.5|TRUE     |              0.639|     1.77|       -0.944|        1.361|
|GR_target      |Sgk1    |          1.770| 0.425| 0.001|  0.000|         323.4|        1103.2|TRUE     |              1.000| 16083.07|        0.734|        2.266|
|GR_target      |Tsc22d3 |         -0.034| 0.523| 0.981|  0.947|        5323.0|        5197.6|TRUE     |              0.477|     0.91|       -0.935|        0.881|
|VDR_pathway    |Med1    |         -0.426| 0.323| 0.433|  0.186|         636.9|         474.0|TRUE     |              0.104|     0.12|       -0.988|        0.216|
|VDR_pathway    |Ncoa1   |         -0.572| 0.411| 0.401|  0.164|         856.1|         575.9|TRUE     |              0.099|     0.11|       -1.235|        0.256|
|VDR_pathway    |Ncoa2   |         -0.471| 0.388| 0.483|  0.225|         688.8|         496.8|TRUE     |              0.129|     0.15|       -1.119|        0.300|
|VDR_pathway    |Ncoa3   |         -0.075| 0.389| 0.939|  0.848|         644.2|         611.4|TRUE     |              0.429|     0.75|       -0.775|        0.646|
|VDR_pathway    |Vdr     |         -0.115| 0.833| 0.956|  0.890|          15.2|          14.0|TRUE     |              0.458|     0.84|       -1.322|        1.186|


:::
:::


### AP-1 candidates — key comparison


::: {.cell}

```{.r .cell-code}
ap1 <- tg |> filter(category == "AP-1") |>
  arrange(desc(log2FoldChange))

knitr::kable(ap1 |> dplyr::select(gene, log2FoldChange, padj, pvalue,
                            mean_norm_CHD, mean_norm_HFD,
                            bayes_P_HFD_gt_CHD, bayes_ER),
  caption="AP-1 family members — ranked by HFD log2FC",
  digits=c(0,3,3,3,1,1,3,2))
```

::: {.cell-output-display}


Table: AP-1 family members — ranked by HFD log2FC

|gene  | log2FoldChange|  padj| pvalue| mean_norm_CHD| mean_norm_HFD| bayes_P_HFD_gt_CHD| bayes_ER|
|:-----|--------------:|-----:|------:|-------------:|-------------:|------------------:|--------:|
|Batf  |          2.167| 0.346|  0.127|           4.5|          20.1|              0.810|     4.27|
|Atf3  |          1.931| 0.053|  0.007|          67.2|         256.4|              0.986|    70.13|
|Junb  |          1.927| 0.012|  0.001|          36.3|         137.4|              0.998|   582.90|
|Fos   |          1.866| 0.034|  0.004|          80.8|         294.0|              0.993|   136.55|
|Ddit3 |          1.051| 0.087|  0.014|         407.1|         843.8|              0.988|    81.05|
|Jund  |          0.377| 0.740|  0.505|         445.2|         578.8|              0.719|     2.56|
|Jun   |          0.206| 0.827|  0.637|         637.0|         735.1|              0.667|     2.00|
|Batf3 |         -0.098| 0.953|  0.882|         129.7|         121.1|              0.451|     0.82|
|Fosl2 |         -0.112| 0.910|  0.788|         945.9|         875.2|              0.402|     0.67|
|Atf4  |         -0.575| 0.386|  0.154|        3406.8|        2287.6|              0.093|     0.10|
|Fosl1 |             NA|    NA|     NA|            NA|            NA|                 NA|       NA|


:::
:::


### AP-1 forest plot


::: {.cell}

```{.r .cell-code}
ap1_ok <- ap1 |> filter(!is.na(log2FoldChange))

ggplot(ap1_ok, aes(x=reorder(gene, log2FoldChange), y=log2FoldChange)) +
  geom_col(aes(fill=log2FoldChange > 0), width=0.6) +
  geom_errorbar(aes(ymin=bayes_CrI_lo, ymax=bayes_CrI_hi), width=0.25) +
  geom_hline(yintercept=0, lty=2) +
  coord_flip() +
  scale_fill_manual(values=c("TRUE"="#d62728","FALSE"="#1f77b4"),
                    labels=c("TRUE"="HFD up","FALSE"="CHD up"), name=NULL) +
  labs(x=NULL, y="log2FC (HFD / CHD), 95% CrI",
       title="AP-1 family — TRAP-seq HFD vs CHD",
       subtitle="Bars = posterior mean; error bars = 95% CrI (Normal(0,1) prior)") +
  theme_classic(base_size=12)
```

::: {.cell-output-display}
![](figures/rnaseq/ap1-forest-1.png){width=2100}
:::
:::


### VDR pathway and GR coactivators


::: {.cell}

```{.r .cell-code}
vdr <- tg |> filter(category == "VDR_pathway") |> arrange(gene)

knitr::kable(vdr |> dplyr::select(gene, log2FoldChange, padj,
                            mean_norm_CHD, mean_norm_HFD,
                            bayes_P_HFD_gt_CHD, bayes_ER),
  caption="VDR pathway and coactivators",
  digits=c(0,3,3,1,1,3,2))
```

::: {.cell-output-display}


Table: VDR pathway and coactivators

|gene  | log2FoldChange|  padj| mean_norm_CHD| mean_norm_HFD| bayes_P_HFD_gt_CHD| bayes_ER|
|:-----|--------------:|-----:|-------------:|-------------:|------------------:|--------:|
|Med1  |         -0.426| 0.433|         636.9|         474.0|              0.104|     0.12|
|Ncoa1 |         -0.572| 0.401|         856.1|         575.9|              0.099|     0.11|
|Ncoa2 |         -0.471| 0.483|         688.8|         496.8|              0.129|     0.15|
|Ncoa3 |         -0.075| 0.939|         644.2|         611.4|              0.429|     0.75|
|Vdr   |         -0.115| 0.956|          15.2|          14.0|              0.458|     0.84|


:::
:::


### Demoted candidates (verification)


::: {.cell}

```{.r .cell-code}
dem <- tg |> filter(category == "demoted") |> arrange(gene)

knitr::kable(dem |> dplyr::select(gene, log2FoldChange, padj,
                            mean_norm_CHD, mean_norm_HFD,
                            bayes_P_HFD_gt_CHD, bayes_ER),
  caption="Demoted candidates — expected to show no significant HFD upregulation",
  digits=c(0,3,3,1,1,3,2))
```

::: {.cell-output-display}


Table: Demoted candidates — expected to show no significant HFD upregulation

|gene  | log2FoldChange|  padj| mean_norm_CHD| mean_norm_HFD| bayes_P_HFD_gt_CHD| bayes_ER|
|:-----|--------------:|-----:|-------------:|-------------:|------------------:|--------:|
|Cebpa |          0.348| 0.833|        2655.5|        3380.1|              0.643|     1.80|
|Cebpb |         -0.503| 0.684|        1218.0|         860.0|              0.254|     0.34|
|Cebpd |          0.909| 0.263|         167.3|         314.5|              0.940|    15.54|
|Foxa1 |         -2.635|    NA|           3.7|           0.6|              0.321|     0.47|
|Foxa2 |             NA|    NA|            NA|            NA|                 NA|       NA|
|Foxo1 |         -0.060| 0.959|        1983.4|        1902.8|              0.452|     0.82|
|Foxo3 |          0.116| 0.870|         566.1|         613.4|              0.638|     1.76|
|Klf13 |          0.530| 0.345|        1193.4|        1723.5|              0.925|    12.42|
|Prrx1 |          0.991| 0.050|         499.2|         991.8|              0.995|   195.39|


:::
:::


### Artifact check (DMRT family)


::: {.cell}

```{.r .cell-code}
dmrt <- tg |> filter(category == "artifact_check")

knitr::kable(dmrt |> dplyr::select(gene, log2FoldChange, padj,
                             mean_norm_CHD, mean_norm_HFD, detected),
  caption="DMRT family — expected to be undetected if motif enrichment was an AT-rich artifact",
  digits=c(0,3,3,1,1,0))
```

::: {.cell-output-display}


Table: DMRT family — expected to be undetected if motif enrichment was an AT-rich artifact

|gene  | log2FoldChange|  padj| mean_norm_CHD| mean_norm_HFD|detected |
|:-----|--------------:|-----:|-------------:|-------------:|:--------|
|Dmrt1 |             NA|    NA|            NA|            NA|FALSE    |
|Dmrt2 |         -1.699| 0.135|        1620.4|         499.5|TRUE     |
|Dmrt3 |             NA|    NA|            NA|            NA|FALSE    |
|Dmrt4 |             NA|    NA|            NA|            NA|FALSE    |


:::
:::


### Functional GR targets


::: {.cell}

```{.r .cell-code}
gr_tg <- tg |> filter(category == "GR_target") |> arrange(desc(log2FoldChange))

knitr::kable(gr_tg |> dplyr::select(gene, log2FoldChange, padj,
                              mean_norm_CHD, mean_norm_HFD,
                              bayes_P_HFD_gt_CHD, bayes_ER),
  caption="Functional GR targets — expected HFD upregulation if GR signalling is sensitized",
  digits=c(0,3,3,1,1,3,2))
```

::: {.cell-output-display}


Table: Functional GR targets — expected HFD upregulation if GR signalling is sensitized

|gene    | log2FoldChange|  padj| mean_norm_CHD| mean_norm_HFD| bayes_P_HFD_gt_CHD| bayes_ER|
|:-------|--------------:|-----:|-------------:|-------------:|------------------:|--------:|
|Lep     |          2.009| 0.014|       14331.1|       57685.3|              0.997|   388.36|
|Angptl4 |          1.949| 0.002|        1978.5|        7638.5|              1.000|  7329.34|
|Sgk1    |          1.770| 0.001|         323.4|        1103.2|              1.000| 16083.07|
|Hsd11b2 |          0.914| 0.634|           7.2|          13.5|              0.733|     2.75|
|Pnpla2  |          0.319| 0.842|        3987.8|        4973.5|              0.639|     1.77|
|Tsc22d3 |         -0.034| 0.981|        5323.0|        5197.6|              0.477|     0.91|
|Nr3c1   |         -0.303| 0.736|        4396.3|        3563.4|              0.269|     0.37|
|Hsd11b1 |         -0.933| 0.110|        1719.2|         900.1|              0.016|     0.02|
|Fkbp5   |         -1.292| 0.010|        1414.6|         578.1|              0.001|     0.00|


:::
:::


---

## 3. ATAC × RNA-seq integration

### Annotate ATAC peaks to nearest gene


::: {.cell}

```{.r .cell-code}
library(GenomicRanges)
library(ChIPseeker)
library(TxDb.Mmusculus.UCSC.mm10.knownGene)
library(org.Mm.eg.db)

atac <- read_tsv(atac_deseq, show_col_types=FALSE) |>
  mutate(.row = row_number())   # keep index; annotatePeak drops non-standard contigs
txdb <- TxDb.Mmusculus.UCSC.mm10.knownGene

# Build GRanges carrying .row so we can left_join back safely
atac_gr <- GRanges(
  seqnames = atac$chr,
  ranges   = IRanges(atac$start + 1, atac$end),
  .row     = atac$.row
)

atac_ann <- annotatePeak(atac_gr, TxDb=txdb, tssRegion=c(-5000, 500),
                         annoDb="org.Mm.eg.db", verbose=FALSE)
```

::: {.cell-output .cell-output-stdout}

```
>> Using Genome: mm10 ...
>> Using Genome: mm10 ...
>> Using Genome: mm10 ...
```


:::

```{.r .cell-code}
atac_ann_df <- as.data.frame(atac_ann)

# left_join instead of bind_cols: peaks on non-standard contigs get NA annotation
atac_full <- atac |>
  left_join(atac_ann_df |> dplyr::select(.row, SYMBOL, distanceToTSS, annotation),
            by = ".row") |>
  dplyr::select(-.row)
```
:::


### Classify ATAC peaks and merge with RNA-seq


::: {.cell}

```{.r .cell-code}
# Classify each ATAC peak by DESeq2 direction
atac_full <- atac_full |>
  mutate(
    atac_dir = case_when(
      !is.na(padj) & padj < 0.05 & log2FoldChange >  1 ~ "HFD_up",
      !is.na(padj) & padj < 0.05 & log2FoldChange < -1 ~ "CHD_up",
      TRUE                                              ~ "shared"
    )
  )

# Join nearest-gene RNA-seq results
deseq_slim <- deseq |>
  dplyr::select(gene, rna_lfc = log2FoldChange, rna_padj = padj) |>
  mutate(rna_lfc  = as.numeric(rna_lfc),
         rna_padj = as.numeric(rna_padj)) |>   # guard: read_tsv may infer character if col starts with NAs
  filter(!is.na(gene))

atac_rna <- atac_full |>
  left_join(deseq_slim, by=c("SYMBOL"="gene"))
```
:::


### Enrichment: are HFD-up ATAC peaks enriched near HFD-upregulated genes?


::: {.cell}

```{.r .cell-code}
# HFD-upregulated gene set (any LFC>0, padj<0.05)
hfd_genes <- deseq |> filter(!is.na(padj) & padj < 0.05 & log2FoldChange > 0) |> pull(gene)

peak_near_hfd_gene <- atac_rna |>
  mutate(near_hfd_gene = SYMBOL %in% hfd_genes)

# 2×2 contingency: atac_dir (HFD_up vs rest) × near_hfd_gene (T/F)
tab <- with(peak_near_hfd_gene,
  table(
    atac    = ifelse(atac_dir == "HFD_up", "HFD_up", "other"),
    rna_up  = near_hfd_gene
  )
)
cat("Contingency table (ATAC direction × nearest gene HFD-up):\n")
```

::: {.cell-output .cell-output-stdout}

```
Contingency table (ATAC direction × nearest gene HFD-up):
```


:::

```{.r .cell-code}
print(tab)
```

::: {.cell-output .cell-output-stdout}

```
        rna_up
atac     FALSE  TRUE
  HFD_up  5697  1203
  other  44393 10326
```


:::

```{.r .cell-code}
ft <- fisher.test(tab, alternative="greater")
cat(sprintf("\nFisher OR=%.2f, p=%.2e\n", ft$estimate, ft$p.value))
```

::: {.cell-output .cell-output-stdout}

```

Fisher OR=1.10, p=1.95e-03
```


:::

```{.r .cell-code}
cat(sprintf("95%% CI: [%.2f, %.2f]\n", ft$conf.int[1], ft$conf.int[2]))
```

::: {.cell-output .cell-output-stdout}

```
95% CI: [1.04, Inf]
```


:::
:::


### Motif stratification: which motif class best predicts paired gene upregulation?


::: {.cell}

```{.r .cell-code}
# Load composite motif counts from ATAC pipeline
motif_file <- "results/motif_analysis/composite_scan/HFD_specific/HFD_specific_per_peak_motifs.tsv"

if (file.exists(motif_file)) {
  motif_map <- c("MA0148.5"="FOXA1","MA0047.5"="FOXA2","MA0466.4"="CEBPB",
                 "MA0102.5"="CEBPA","MA0480.3"="FOXO1","MA0113.4"="NR3C1",
                 "MA2327.1"="PGR_h","MA2323.1"="PGR_m")

  hfd_motifs <- read_tsv(motif_file, show_col_types=FALSE)
  names(hfd_motifs) <- ifelse(names(hfd_motifs) %in% names(motif_map),
                              motif_map[names(hfd_motifs)], names(hfd_motifs))

  # Need to also load AP-1 and VDR motifs from the full-motif scan
  full_scan_file <- "results/motif_analysis/full_motif_scan/HFD_specific/HFD_specific_per_peak_all_motifs.tsv"

  if (file.exists(full_scan_file)) {
    full_motifs <- read_tsv(full_scan_file, show_col_types=FALSE)

    # AP-1 motifs in JASPAR 2024 (representative IDs; from FULL_MOTIF_SCAN output)
    ap1_ids  <- grep("^MA0(099|478|099|477|153|162|039|063|099)",
                     names(full_motifs), value=TRUE)
    # VDR motif
    vdr_ids  <- grep("MA0693", names(full_motifs), value=TRUE)

    hfd_motifs$has_ap1 <- if (length(ap1_ids)) rowSums(full_motifs[, ap1_ids, drop=FALSE]) > 0 else FALSE
    hfd_motifs$has_vdr <- if (length(vdr_ids)) rowSums(full_motifs[, vdr_ids, drop=FALSE]) > 0 else FALSE
  } else {
    hfd_motifs$has_ap1 <- FALSE
    hfd_motifs$has_vdr <- FALSE
    message("Full motif scan not found — AP-1/VDR stratification skipped")
  }

  # GR motif
  gr_cols <- intersect(c("NR3C1","PGR_h","PGR_m"), names(hfd_motifs))
  hfd_motifs$has_gr <- if (length(gr_cols)) rowSums(hfd_motifs[, gr_cols, drop=FALSE]) > 0 else FALSE

  # Motif class assignment
  hfd_motifs <- hfd_motifs |>
    mutate(
      motif_class = case_when(
        has_ap1 & has_gr & !has_vdr ~ "AP1_GR",
        has_vdr & has_gr & !has_ap1 ~ "VDR_GR",
        has_ap1 & has_vdr & has_gr  ~ "AP1_VDR_GR",
        has_gr  & !has_ap1 & !has_vdr ~ "GR_only",
        has_ap1 & !has_gr  ~ "AP1_only",
        has_vdr & !has_gr  ~ "VDR_only",
        TRUE                ~ "none"
      )
    )

  # Parse peak coordinates from FASTA-style peak IDs
  peak_coords <- hfd_motifs |>
    mutate(
      chr   = sub(":.*", "", peak),
      start = as.integer(sub(".*:(\\d+)-.*", "\\1", peak)),
      end   = as.integer(sub(".*-", "", peak))
    )

  # Join to ATAC+RNA table via chr/start/end overlap (nearest match by start)
  hfd_peaks_rna <- atac_rna |>
    filter(atac_dir == "HFD_up") |>
    left_join(peak_coords |> dplyr::select(chr, start, end, motif_class),
              by=c("chr","start","end"))

  # Per motif class: fraction with HFD-up nearest gene
  strat <- hfd_peaks_rna |>
    filter(!is.na(motif_class)) |>
    group_by(motif_class) |>
    summarise(
      n_peaks      = n(),
      n_near_hfd   = sum(SYMBOL %in% hfd_genes, na.rm=TRUE),
      pct_near_hfd = round(100 * n_near_hfd / n_peaks, 1),
      .groups="drop"
    ) |>
    arrange(desc(pct_near_hfd))

  knitr::kable(strat,
    caption="HFD-up ATAC peaks: fraction near HFD-upregulated genes, by motif class")

  # Fisher test: each motif class vs GR_only
  gr_only  <- hfd_peaks_rna |> filter(motif_class == "GR_only")
  gr_n_up  <- sum(gr_only$SYMBOL %in% hfd_genes, na.rm=TRUE)
  gr_n_tot <- nrow(gr_only)

  fisher_vs_gr <- function(class_label) {
    cl <- hfd_peaks_rna |> filter(motif_class == class_label)
    if (nrow(cl) < 5) return(NULL)
    tab <- matrix(c(sum(cl$SYMBOL %in% hfd_genes, na.rm=TRUE), nrow(cl),
                    gr_n_up, gr_n_tot), nrow=2)
    ft  <- fisher.test(tab)
    tibble(motif_class=class_label, n=nrow(cl),
           pct=round(100*tab[1,1]/nrow(cl),1),
           OR=round(ft$estimate,2), p=signif(ft$p.value,3))
  }

  classes <- setdiff(unique(hfd_peaks_rna$motif_class), c("GR_only",NA))
  fisher_res <- bind_rows(lapply(classes, fisher_vs_gr))
  knitr::kable(fisher_res,
    caption="Motif class vs GR-only: enrichment near HFD-up genes (Fisher exact)")
} else {
  cat("Composite motif scan output not found — run ATAC pipeline first.\n")
}
```

::: {.cell-output-display}


Table: Motif class vs GR-only: enrichment near HFD-up genes (Fisher exact)

|motif_class |  n| pct| OR|  p|
|:-----------|--:|---:|--:|--:|
|AP1_only    |  5|   0|  0|  1|


:::
:::


---

## 4. Locus tracks

BigWig files generated by `RNASEQ_BIGWIG` (CPM-normalised, 50bp bins) and
`ATAC_BIGWIG` (RPGC-normalised, 10bp bins) are at:

- RNA-seq: `results/rnaseq/bigwig/<sample_id>.CPM.bw`
- ATAC:    `results/bigwig/atac/<sample_id>.RPGC.bw`

Track ranges below are for mm10.  Visualisation uses pyGenomeTracks or IGV.


::: {.cell}

```{.r .cell-code}
loci <- tribble(
  ~gene,    ~chr,   ~start,     ~end,
  "Hsd11b1","chr1",  4819895,    4920000,
  "Fkbp5",  "chr4",  99948700,  100065000,
  "Vdr",    "chr15", 97844000,   97908000,
  "Junb",   "chr8",  84786000,   84800000,
  "Fosl2",  "chr5",  32356000,   32400000
)
knitr::kable(loci, caption="Locus coordinates for track visualisation (mm10)")
```

::: {.cell-output-display}


Table: Locus coordinates for track visualisation (mm10)

|gene    |chr   |    start|       end|
|:-------|:-----|--------:|---------:|
|Hsd11b1 |chr1  |  4819895|   4920000|
|Fkbp5   |chr4  | 99948700| 100065000|
|Vdr     |chr15 | 97844000|  97908000|
|Junb    |chr8  | 84786000|  84800000|
|Fosl2   |chr5  | 32356000|  32400000|


:::
:::


The following code renders condition-averaged normalised coverage using
`wiggletools` mean across replicates, then `bigWigToBedGraph` + summary
stats. For IGV batch rendering, load bigWigs directly from the paths above.


::: {.cell}

```{.r .cell-code}
# Shell commands to merge per-condition BigWigs (requires wiggletools + UCSC tools)
# Run from the GSE236575 directory.

conds <- c("CHD", "HFD")
types <- c(
  list(tag="atac", dir="results/bigwig/atac",    suffix=".RPGC.bw"),
  list(tag="rna",  dir="results/rnaseq/bigwig",  suffix=".CPM.bw")
)

for (cond in conds) {
  for (t in types) {
    bws <- paste(
      file.path(t$dir, paste0(cond, "_", 1:3, t$suffix)),
      collapse=" "
    )
    cmd <- sprintf(
      "wiggletools mean %s | wigToBigWig -fixedStep stdin results/genome/mm10.chrom.sizes %s/%s_%s_mean.bw",
      bws, t$dir, cond, t$tag
    )
    cat(cmd, "\n")
  }
}
```
:::


---

## 5. Decision outputs

### 5.1 AP-1 lead candidate (Junb vs Fosl2)


::: {.cell}

```{.r .cell-code}
ap1_key <- tg |>
  filter(gene %in% c("Junb","Fosl2")) |>
  dplyr::select(gene, log2FoldChange, padj, mean_norm_CHD, mean_norm_HFD,
         bayes_P_HFD_gt_CHD, bayes_ER, bayes_CrI_lo, bayes_CrI_hi)

knitr::kable(ap1_key, digits=c(0,3,3,1,1,3,2,3,3),
  caption="Junb vs Fosl2 — head-to-head comparison for AP-1 lead candidate selection")
```

::: {.cell-output-display}


Table: Junb vs Fosl2 — head-to-head comparison for AP-1 lead candidate selection

|gene  | log2FoldChange|  padj| mean_norm_CHD| mean_norm_HFD| bayes_P_HFD_gt_CHD| bayes_ER| bayes_CrI_lo| bayes_CrI_hi|
|:-----|--------------:|-----:|-------------:|-------------:|------------------:|--------:|------------:|------------:|
|Fosl2 |         -0.112| 0.910|         945.9|         875.2|              0.402|     0.67|       -0.846|        0.656|
|Junb  |          1.927| 0.012|          36.3|         137.4|              0.998|   582.90|        0.480|        2.425|


:::

```{.r .cell-code}
cat("\n--- AP-1 lead candidate verdict ---\n")
```

::: {.cell-output .cell-output-stdout}

```

--- AP-1 lead candidate verdict ---
```


:::

```{.r .cell-code}
junb  <- ap1_key |> filter(gene=="Junb")
fosl2 <- ap1_key |> filter(gene=="Fosl2")

if (nrow(junb) && nrow(fosl2) && !is.na(junb$log2FoldChange) && !is.na(fosl2$log2FoldChange)) {
  lead <- if (junb$log2FoldChange > fosl2$log2FoldChange) "Junb" else "Fosl2"
  cat(sprintf("Lead AP-1 candidate by HFD log2FC: %s (LFC=%.3f vs %.3f)\n",
              lead, junb$log2FoldChange, fosl2$log2FoldChange))
  cat(sprintf("Bayesian P(HFD>CHD): Junb=%.3f, Fosl2=%.3f\n",
              junb$bayes_P_HFD_gt_CHD, fosl2$bayes_P_HFD_gt_CHD))
} else {
  cat("One or both genes not detected — see targeted gene table.\n")
}
```

::: {.cell-output .cell-output-stdout}

```
Lead AP-1 candidate by HFD log2FC: Junb (LFC=1.927 vs -0.112)
Bayesian P(HFD>CHD): Junb=0.998, Fosl2=0.402
```


:::
:::


### 5.2 DMRT family expression status


::: {.cell}

```{.r .cell-code}
dmrt <- tg |> filter(category == "artifact_check") |>
  dplyr::select(gene, mean_norm_CHD, mean_norm_HFD, detected, log2FoldChange, padj)

knitr::kable(dmrt, caption="DMRT family expression status",
             digits=c(0,1,1,0,3,3))
```

::: {.cell-output-display}


Table: DMRT family expression status

|gene  | mean_norm_CHD| mean_norm_HFD|detected | log2FoldChange|  padj|
|:-----|-------------:|-------------:|:--------|--------------:|-----:|
|Dmrt1 |            NA|            NA|FALSE    |             NA|    NA|
|Dmrt2 |        1620.4|         499.5|TRUE     |         -1.699| 0.135|
|Dmrt3 |            NA|            NA|FALSE    |             NA|    NA|
|Dmrt4 |            NA|            NA|FALSE    |             NA|    NA|


:::

```{.r .cell-code}
cat("\n--- DMRT verdict ---\n")
```

::: {.cell-output .cell-output-stdout}

```

--- DMRT verdict ---
```


:::

```{.r .cell-code}
if (all(!dmrt$detected, na.rm=TRUE)) {
  cat("DMRT1-4 are undetected (mean normalised count < 5 in both conditions).\n")
  cat("Verdict: AT-rich motif enrichment is an artifact; DMRT family are not expressed in eWAT adipocytes.\n")
} else {
  detected_dmrts <- dmrt |> filter(detected) |> pull(gene)
  cat("DETECTED:", paste(detected_dmrts, collapse=", "), "\n")
  cat("Verdict: requires manual review — unexpected DMRT expression in adipocytes.\n")
}
```

::: {.cell-output .cell-output-stdout}

```
DETECTED: Dmrt2 
Verdict: requires manual review — unexpected DMRT expression in adipocytes.
```


:::
:::


### 5.3 Coactivator and HSD11B1 expression status


::: {.cell}

```{.r .cell-code}
coact <- tg |> filter(gene %in% c("Ncoa1","Ncoa2","Ncoa3","Med1","Hsd11b1","Hsd11b2")) |>
  dplyr::select(gene, log2FoldChange, padj, mean_norm_CHD, mean_norm_HFD,
         bayes_P_HFD_gt_CHD, bayes_ER)

knitr::kable(coact, digits=c(0,3,3,1,1,3,2),
  caption="Coactivators and HSD11B1 — expression and HFD regulation")
```

::: {.cell-output-display}


Table: Coactivators and HSD11B1 — expression and HFD regulation

|gene    | log2FoldChange|  padj| mean_norm_CHD| mean_norm_HFD| bayes_P_HFD_gt_CHD| bayes_ER|
|:-------|--------------:|-----:|-------------:|-------------:|------------------:|--------:|
|Hsd11b1 |         -0.933| 0.110|        1719.2|         900.1|              0.016|     0.02|
|Hsd11b2 |          0.914| 0.634|           7.2|          13.5|              0.733|     2.75|
|Med1    |         -0.426| 0.433|         636.9|         474.0|              0.104|     0.12|
|Ncoa1   |         -0.572| 0.401|         856.1|         575.9|              0.099|     0.11|
|Ncoa2   |         -0.471| 0.483|         688.8|         496.8|              0.129|     0.15|
|Ncoa3   |         -0.075| 0.939|         644.2|         611.4|              0.429|     0.75|


:::

```{.r .cell-code}
cat("\n--- Coactivator/HSD11B1 verdict ---\n")
```

::: {.cell-output .cell-output-stdout}

```

--- Coactivator/HSD11B1 verdict ---
```


:::

```{.r .cell-code}
for (g in c("Ncoa1","Ncoa2","Ncoa3","Med1","Hsd11b1","Hsd11b2")) {
  row <- tg |> filter(gene == g)
  if (nrow(row) == 0 || is.na(row$log2FoldChange)) {
    cat(sprintf("  %s: not detected\n", g))
  } else {
    direction <- if (row$log2FoldChange > 0) "HFD-up" else "HFD-down"
    sig       <- if (!is.na(row$padj) && row$padj < 0.05) "sig" else "ns"
    cat(sprintf("  %s: LFC=%.3f, padj=%.3f (%s %s), P(HFD>CHD)=%.3f\n",
                g, row$log2FoldChange, row$padj, direction, sig,
                row$bayes_P_HFD_gt_CHD))
  }
}
```

::: {.cell-output .cell-output-stdout}

```
  Ncoa1: LFC=-0.572, padj=0.401 (HFD-down ns), P(HFD>CHD)=0.099
  Ncoa2: LFC=-0.471, padj=0.483 (HFD-down ns), P(HFD>CHD)=0.129
  Ncoa3: LFC=-0.075, padj=0.939 (HFD-down ns), P(HFD>CHD)=0.429
  Med1: LFC=-0.426, padj=0.433 (HFD-down ns), P(HFD>CHD)=0.104
  Hsd11b1: LFC=-0.933, padj=0.110 (HFD-down ns), P(HFD>CHD)=0.016
  Hsd11b2: LFC=0.914, padj=0.634 (HFD-up ns), P(HFD>CHD)=0.733
```


:::
:::


---

## 6. AP-1 motif scan at the Fkbp5 locus

**Hypothesis:** Fkbp5 is a Junb-repressed gene. If AP-1 motifs are present in
the Fkbp5 regulatory landscape and Junb ChIP signal is detectable there, the
two mechanisms (AP-1 chromatin remodelling + Fkbp5-mediated GR de-repression)
collapse into one Junb-led cascade: HFD to Junb up to AP-1 chromatin opening at
GR cooperative sites AND Fkbp5 down to constitutive GR nuclear activity.

Fkbp5 is on the **minus strand**, chr4:99,946,395-100,067,558 (mm10).
TSS approx chr4:100,067,500. Known GREs reside in introns 2 and 4.

### 6.1 ATAC-seq peaks at the Fkbp5 locus


::: {.cell}

```{.r .cell-code}
fkbp5_chr   <- "chr4"
fkbp5_start <- 99936000L
fkbp5_end   <- 100078000L

fkbp5_peaks <- atac_rna |>
  filter(chr == fkbp5_chr,
         start >= fkbp5_start,
         end   <= fkbp5_end) |>
  dplyr::select(chr, start, end, log2FoldChange, padj, atac_dir,
                SYMBOL, distanceToTSS, rna_lfc, rna_padj) |>
  arrange(start)

cat(sprintf("ATAC peaks at Fkbp5 locus (%s:%d-%d): %d\n",
            fkbp5_chr, fkbp5_start, fkbp5_end, nrow(fkbp5_peaks)))
```

::: {.cell-output .cell-output-stdout}

```
ATAC peaks at Fkbp5 locus (chr4:99936000-100078000): 10
```


:::

```{.r .cell-code}
cat(sprintf("  HFD-up : %d\n", sum(fkbp5_peaks$atac_dir == "HFD_up")))
```

::: {.cell-output .cell-output-stdout}

```
  HFD-up : 0
```


:::

```{.r .cell-code}
cat(sprintf("  CHD-up : %d\n", sum(fkbp5_peaks$atac_dir == "CHD_up")))
```

::: {.cell-output .cell-output-stdout}

```
  CHD-up : 0
```


:::

```{.r .cell-code}
cat(sprintf("  shared : %d\n", sum(fkbp5_peaks$atac_dir == "shared")))
```

::: {.cell-output .cell-output-stdout}

```
  shared : 10
```


:::

```{.r .cell-code}
knitr::kable(
  fkbp5_peaks |>
    mutate(across(c(log2FoldChange, rna_lfc), ~round(as.numeric(.), 3)),
           across(c(padj, rna_padj), ~signif(as.numeric(.), 2)),
           distanceToTSS = round(distanceToTSS / 1000, 1)),
  caption = "ATAC peaks at the Fkbp5 locus (distanceToTSS in kb)"
)
```

::: {.cell-output-display}


Table: ATAC peaks at the Fkbp5 locus (distanceToTSS in kb)

|chr  |     start|       end| log2FoldChange|  padj|atac_dir |SYMBOL  | distanceToTSS|  rna_lfc| rna_padj|
|:----|---------:|---------:|--------------:|-----:|:--------|:-------|-------------:|--------:|--------:|
|chr4 |  99939312|  99940563|         -0.466| 0.061|shared   |Itgb3bp |          -9.5|  200.826|       NA|
|chr4 |  99941324|  99942488|         -0.455| 0.075|shared   |Itgb3bp |         -11.5|  200.826|       NA|
|chr4 |  99947228|  99947653|         -0.364| 0.500|shared   |Pgm1    |          -8.1| 1974.368|       NA|
|chr4 |  99956954|  99957439|         -0.378| 0.480|shared   |Pgm1    |           1.2| 1974.368|       NA|
|chr4 |  99968583|  99970148|         -0.669| 0.019|shared   |Pgm1    |          12.8| 1974.368|       NA|
|chr4 |  99973865|  99975020|         -0.570| 0.059|shared   |Pgm1    |          18.1| 1974.368|       NA|
|chr4 | 100004453| 100004834|         -0.537| 0.530|shared   |Pgm1    |          48.7| 1974.368|       NA|
|chr4 | 100008258| 100009299|         -0.358| 0.390|shared   |Pgm1    |          52.5| 1974.368|       NA|
|chr4 | 100011064| 100011964|         -0.165| 0.750|shared   |Pgm1    |          55.3| 1974.368|       NA|
|chr4 | 100041738| 100042498|         -0.640| 0.260|shared   |Ror1    |         -53.3|   47.553|       NA|


:::
:::


### 6.1a Fkbp5 locus — ATAC signal panel (CHD vs HFD)


::: {.cell}

```{.r .cell-code}
select <- dplyr::select

# Normalized counts (row = peak_id, col = sample)
cnts_mat <- read.table("results/deseq2/deseq2_normalized_counts.txt",
                       header = TRUE, row.names = 1, sep = "\t", check.names = FALSE)
cnts_long <- cnts_mat |>
  rownames_to_column("peak_id") |>
  pivot_longer(-peak_id, names_to = "sample", values_to = "norm_count") |>
  mutate(condition = ifelse(grepl("^CHD", sample), "CHD", "HFD"))

# Full peak data with per-sample counts
atac_counts <- read_tsv("results/deseq2/deseq2_results.txt", show_col_types = FALSE) |>
  left_join(cnts_long, by = "peak_id") |>
  mutate(mid_kb = (start + end) / 2e3)

# Helper: summarise counts at a locus into plottable long form
locus_counts <- function(chr_in, s, e) {
  atac_counts |>
    filter(chr == chr_in, start >= s, end <= e) |>
    group_by(peak_id, chr, start, end, log2FoldChange, padj, mid_kb) |>
    summarise(
      CHD    = mean(norm_count[condition == "CHD"]),
      HFD    = mean(norm_count[condition == "HFD"]),
      CHD_se = sd(norm_count[condition == "CHD"]) / sqrt(3),
      HFD_se = sd(norm_count[condition == "HFD"]) / sqrt(3),
      .groups = "drop"
    ) |>
    mutate(
      sig = case_when(padj < 0.001 ~ "***", padj < 0.01 ~ "**",
                      padj < 0.05  ~ "*",   TRUE         ~ "")
    ) |>
    pivot_longer(c(CHD, HFD), names_to = "condition", values_to = "mean_cnt") |>
    mutate(se = ifelse(condition == "CHD", CHD_se, HFD_se),
           peak_label = sprintf("%.1f kb", mid_kb))
}

fkbp5_cts <- locus_counts("chr4", 99900000, 100100000) |>
  mutate(condition = factor(condition, levels = c("CHD", "HFD")),
         peak_label = fct_reorder(peak_label, mid_kb))

# Significance label shown once (on HFD bar)
sig_labels <- fkbp5_cts |>
  filter(condition == "HFD", sig != "") |>
  mutate(y_pos = mean_cnt + se + max(fkbp5_cts$mean_cnt) * 0.06)

ggplot(fkbp5_cts, aes(x = peak_label, y = mean_cnt, fill = condition)) +
  geom_col(position = position_dodge(0.75), width = 0.7) +
  geom_errorbar(aes(ymin = mean_cnt - se, ymax = mean_cnt + se),
                position = position_dodge(0.75), width = 0.25) +
  geom_text(data = sig_labels,
            aes(x = peak_label, y = y_pos, label = sig),
            inherit.aes = FALSE, size = 4, hjust = 0.5) +
  scale_fill_manual(values = color_scheme, name = "Diet") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.12))) +
  labs(
    title    = "Fkbp5 locus — ATAC-seq normalised counts",
    subtitle = "Each bar = one peak; * padj < 0.05  ** padj < 0.01  *** padj < 0.001 (DESeq2)",
    x        = "Peak mid-point (genomic position, kb)",
    y        = "Mean normalised ATAC count ± SE"
  ) +
  theme_classic(base_size = 11) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8),
        legend.position = "top")
```

::: {.cell-output-display}
![](figures/rnaseq/fkbp5-locus-panel-1.png){width=2400}
:::
:::


> **Interpretation:** Every peak across the 200-kb Fkbp5 locus shows CHD ≥ HFD
> signal — chromatin is systematically more accessible in chow-diet adipocytes.
> Two peaks are formally significant (padj < 0.05): chr4:99,929,264 (upstream
> regulatory region) and chr4:99,968,583 (gene body). This is the chromatin
> correlate of the Fkbp5 downregulation seen in TRAP-seq (LFC = −1.29,
> padj = 0.010) and supports AP-1-mediated silencing at this locus in HFD.

### 6.2 AP-1 motif scan


::: {.cell}

```{.r .cell-code}
suppressPackageStartupMessages({
  library(BSgenome.Mmusculus.UCSC.mm10)
  library(JASPAR2024)
  library(TFBSTools)
  library(Biostrings)
})

# JASPAR2024 R package ships only metadata.csv with an incompatible SQLite schema.
# Strategy: (1) use JASPAR2020 local DB if installed (compatible TFBSTools schema),
#           (2) download the JASPAR 2024 CORE vertebrates flat file from the website.
pfm_list_all <- NULL

if (requireNamespace("JASPAR2020", quietly = TRUE)) {
  db2020 <- system.file("extdata", "JASPAR2020.sqlite", package = "JASPAR2020")
  if (nzchar(db2020) && file.exists(db2020)) {
    pfm_list_all <- TFBSTools::getMatrixSet(
      db2020,
      opts = list(collection = "CORE", tax_group = "vertebrates", all_versions = FALSE)
    )
    cat("Loaded", length(pfm_list_all), "motifs from JASPAR2020 (vertebrates)\n")
  }
}
```

::: {.cell-output .cell-output-stdout}

```
Loaded 746 motifs from JASPAR2020 (vertebrates)
```


:::

```{.r .cell-code}
if (is.null(pfm_list_all)) {
  tmp_jaspar <- tempfile(fileext = ".jaspar")
  dl <- tryCatch(
    httr::GET(
      paste0("https://jaspar.elixir.no/download/data/2024/CORE/",
             "JASPAR2024_CORE_vertebrates_non-redundant_pfms.jaspar"),
      httr::write_disk(tmp_jaspar, overwrite = TRUE),
      httr::timeout(60)
    ),
    error = function(e) { message("Download failed: ", e$message); NULL }
  )
  if (!is.null(dl) && !httr::http_error(dl)) {
    pfm_list_all <- TFBSTools::readJASPARMatrix(tmp_jaspar, matrixClass = "PFMatrix")
    cat("Loaded", length(pfm_list_all), "motifs from JASPAR 2024 download\n")
  }
}

if (is.null(pfm_list_all))
  stop("Could not load JASPAR motifs: install JASPAR2020 or ensure internet access")

ap1_motifs <- pfm_list_all[
  grepl("JUN|FOS|ATF|BATF|NFE2|MAFK|MAFF",
        sapply(pfm_list_all, function(x) x@name),
        ignore.case = TRUE)
]
cat(sprintf("AP-1 family motifs selected: %d\n", length(ap1_motifs)))
```

::: {.cell-output .cell-output-stdout}

```
AP-1 family motifs selected: 45
```


:::

```{.r .cell-code}
scan_gr  <- GRanges("chr4", IRanges(fkbp5_start, fkbp5_end))
scan_seq <- getSeq(BSgenome.Mmusculus.UCSC.mm10, scan_gr)
names(scan_seq) <- "Fkbp5_locus"

pwm_list  <- toPWM(ap1_motifs)
# Build hits tibble directly from S4 slots — as.data.frame(SiteSetList) produces
# inconsistent column names across TFBSTools versions; slot access is reliable.
hits_list <- lapply(names(pwm_list), function(id) {
  ssl <- searchSeq(pwm_list[[id]], scan_seq,
                   seqname = "Fkbp5_locus",
                   min.score = "85%", strand = "*")
  # searchSeq on a DNAStringSet returns a SiteSetList; [[1]] gives the SiteSet
  ss <- ssl[[1]]
  if (length(ss) == 0) return(NULL)
  tibble(
    start      = as.integer(start(ss@views)),
    end        = as.integer(end(ss@views)),
    strand     = as.character(ss@strand),
    score      = as.numeric(ss@score),
    motif_id   = id,
    motif_name = pwm_list[[id]]@name
  )
})
hits_df <- bind_rows(hits_list) |>
  mutate(
    mm10_pos    = fkbp5_start + start - 1L,
    dist_to_tss = 100067500L - mm10_pos,
    region = case_when(
      mm10_pos >= 100062500 & mm10_pos <= 100072500 ~ "promoter (+-5 kb)",
      mm10_pos >= 99946395  & mm10_pos <= 100067558 ~ "gene body",
      TRUE                                          ~ "flanking"
    )
  )

cat(sprintf("Total AP-1 hits (>=85%% score): %d\n", nrow(hits_df)))
```

::: {.cell-output .cell-output-stdout}

```
Total AP-1 hits (>=85% score): 6635
```


:::

```{.r .cell-code}
cat("\nHits by region:\n"); print(table(hits_df$region))
```

::: {.cell-output .cell-output-stdout}

```

Hits by region:
```


:::

::: {.cell-output .cell-output-stdout}

```

         flanking         gene body promoter (+-5 kb) 
              768              5325               542 
```


:::

```{.r .cell-code}
cat("\nHits by TF:\n");     print(sort(table(hits_df$motif_name), decreasing = TRUE))
```

::: {.cell-output .cell-output-stdout}

```

Hits by TF:
```


:::

::: {.cell-output .cell-output-stdout}

```

       JUND(var.2)              FOSL2                JUN        FOSL2::JUND 
               481                446                402                351 
        JUN(var.2)         FOSB::JUNB        FOSL1::JUND               Atf1 
               340                313                303                301 
        FOSL2::JUN        FOSL2::JUNB                FOS           FOS::JUN 
               300                296                258                256 
         FOS::JUND          FOS::JUNB         FOSL1::JUN          JUN::JUNB 
               251                168                161                161 
              BATF          BATF::JUN               ATF3               NFE2 
               151                138                133                129 
             BATF3              FOSL1        FOSL1::JUNB               JUNB 
               128                125                120                 97 
FOSL1::JUND(var.2)               JUND  FOSB::JUNB(var.2)               ATF2 
                92                 90                 64                 63 
 FOSL2::JUN(var.2)          MAF::NFE2  FOSL1::JUN(var.2) FOSL2::JUNB(var.2) 
                58                 47                 46                 45 
              ATF4               ATF7        Bach1::Mafk   JUN::JUNB(var.2) 
                43                 38                 33                 32 
         FOSB::JUN               MAFF FOSL2::JUND(var.2)             Nfe2l2 
                28                 24                 23                 23 
              MAFK             NFE2L1        JUNB(var.2)               ATF6 
                21                 18                 16                 11 
   FOS::JUN(var.2) 
                11 
```


:::
:::



::: {.cell}

```{.r .cell-code}
gre_pos <- tibble(
  label    = c("GRE intron2a", "GRE intron2b", "GRE intron4"),
  mm10_pos = c(100015000L, 100008000L, 99970000L)
)

hits_plot <- hits_df |>
  filter(region %in% c("promoter (+-5 kb)", "gene body")) |>
  mutate(motif_family = case_when(
    grepl("JUN|JUNB|JUND",  motif_name, ignore.case = TRUE) ~ "Jun",
    grepl("FOS|FOSL|FOSB",  motif_name, ignore.case = TRUE) ~ "Fos",
    grepl("ATF",            motif_name, ignore.case = TRUE) ~ "ATF",
    grepl("BATF",           motif_name, ignore.case = TRUE) ~ "BATF",
    TRUE                                                    ~ "other AP-1"
  ))

ggplot() +
  annotate("rect",
           xmin = 99946395, xmax = 100067558, ymin = -0.4, ymax = 0.4,
           fill = "grey85", alpha = 0.5) +
  annotate("text", x = 100006000, y = 0.55,
           label = "Fkbp5 gene body", size = 3, color = "grey40") +
  annotate("segment",
           x = 100067500, xend = 100062000, y = 0, yend = 0,
           arrow = arrow(length = unit(0.15, "cm")),
           color = "black", linewidth = 0.8) +
  annotate("text", x = 100068500, y = 0.15, label = "TSS", size = 3) +
  geom_vline(data = gre_pos,
             aes(xintercept = mm10_pos),
             lty = 2, color = "#e377c2", linewidth = 0.7) +
  geom_text(data = gre_pos,
            aes(x = mm10_pos, y = -0.65, label = label),
            size = 2.5, color = "#e377c2", angle = 90, hjust = 0) +
  geom_rug(data = hits_plot,
           aes(x = mm10_pos, color = motif_family),
           sides = "t", linewidth = 0.9, alpha = 0.85,
           length = unit(0.07, "npc")) +
  scale_color_manual(
    values = c(Jun = "#d62728", Fos = "#1f77b4", ATF = "#ff7f0e",
               BATF = "#2ca02c", "other AP-1" = "grey50"),
    name = "Motif family"
  ) +
  scale_x_continuous(
    labels = function(x) sprintf("%.2f Mb", x / 1e6),
    limits = c(fkbp5_start, fkbp5_end)
  ) +
  labs(x = "chr4 (mm10)", y = NULL,
       title = "AP-1 motif hits at the Fkbp5 locus (JASPAR 2024, >=85% score)",
       subtitle = "Pink dashed = known GRE positions; rug = AP-1 motif hit") +
  theme_classic(base_size = 11) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        panel.grid.major.x = element_line(color = "grey90"))
```

::: {.cell-output-display}
![](figures/rnaseq/fkbp5-motif-plot-1.png){width=3000}
:::
:::



::: {.cell}

```{.r .cell-code}
top_hits <- hits_df |>
  filter(region %in% c("promoter (+-5 kb)", "gene body")) |>
  arrange(desc(score)) |>
  slice_head(n = 20) |>
  dplyr::select(motif_name, motif_id, mm10_pos, dist_to_tss,
                strand, score, region) |>
  mutate(dist_to_tss = round(dist_to_tss / 1000, 2),
         score       = round(score, 3))

knitr::kable(top_hits,
  caption = "Top 20 AP-1 motif hits at Fkbp5 (>=85%, by score). dist_to_tss in kb.")
```

::: {.cell-output-display}


Table: Top 20 AP-1 motif hits at Fkbp5 (>=85%, by score). dist_to_tss in kb.

|motif_name         |motif_id |  mm10_pos| dist_to_tss|strand |  score|region    |
|:------------------|:--------|---------:|-----------:|:------|------:|:---------|
|ATF4               |MA0833.2 |  99990453|       77.05|-      | 18.133|gene body |
|MAFF               |MA0495.3 |  99969605|       97.89|-      | 17.790|gene body |
|ATF7               |MA0834.1 |  99982434|       85.07|-      | 17.534|gene body |
|MAF::NFE2          |MA0501.1 | 100056502|       11.00|-      | 17.127|gene body |
|JUN::JUNB(var.2)   |MA1133.1 |  99982435|       85.06|+      | 17.094|gene body |
|ATF2               |MA1632.1 | 100035286|       32.21|+      | 16.965|gene body |
|ATF7               |MA0834.1 |  99982434|       85.07|+      | 16.630|gene body |
|ATF3               |MA0605.2 |  99982435|       85.06|+      | 16.594|gene body |
|ATF3               |MA0605.2 |  99982435|       85.06|-      | 16.584|gene body |
|JUNB(var.2)        |MA1140.2 |  99982435|       85.06|-      | 16.508|gene body |
|FOS::JUN(var.2)    |MA1126.1 |  99982435|       85.06|+      | 16.455|gene body |
|JUN(var.2)         |MA0489.1 |  99967729|       99.77|+      | 16.449|gene body |
|FOSL2::JUNB(var.2) |MA1139.1 |  99982435|       85.06|+      | 16.394|gene body |
|FOSL2::JUNB(var.2) |MA1139.1 |  99982435|       85.06|-      | 16.381|gene body |
|ATF4               |MA0833.2 | 100026366|       41.13|-      | 16.359|gene body |
|ATF4               |MA0833.2 |  99961506|      105.99|-      | 16.269|gene body |
|FOSL2::JUND(var.2) |MA1145.1 |  99982433|       85.07|-      | 16.171|gene body |
|FOSB::JUNB(var.2)  |MA1136.1 |  99982436|       85.06|+      | 15.965|gene body |
|FOSL2::JUN(var.2)  |MA1131.1 |  99982435|       85.06|+      | 15.941|gene body |
|ATF2               |MA1632.1 |  99993809|       73.69|+      | 15.842|gene body |


:::
:::


### 6.3 ChIP-Atlas: Junb binding evidence at Fkbp5


::: {.cell}

```{.r .cell-code}
library(httr)

query_chipatlas <- function(distance) {
  url <- sprintf(
    "https://chip-atlas.dbcls.jp/api/target?assemblyId=mm10&factor=Junb&gene=Fkbp5&distance=%d",
    distance
  )
  cat(sprintf("Querying ChIP-Atlas (dist=%d bp)\n", distance))
  tryCatch({
    resp <- GET(url, timeout(30))
    if (status_code(resp) == 200) {
      raw <- content(resp, as = "text", encoding = "UTF-8")
      if (nchar(trimws(raw)) < 5)
        return(tibble(result = sprintf("No Junb peaks within %d bp of Fkbp5 TSS", distance)))
      read_tsv(I(raw), show_col_types = FALSE)
    } else {
      tibble(result = sprintf("HTTP %d", status_code(resp)))
    }
  }, error = function(e) tibble(result = conditionMessage(e)))
}

ca_result <- query_chipatlas(1000)
```

::: {.cell-output .cell-output-stdout}

```
Querying ChIP-Atlas (dist=1000 bp)
```


:::

```{.r .cell-code}
if ("result" %in% names(ca_result) && grepl("No Junb", ca_result$result))
  ca_result <- query_chipatlas(5000)

knitr::kable(ca_result,
  caption = "ChIP-Atlas: public Junb ChIP-seq experiments with peaks near Fkbp5 TSS")
```

::: {.cell-output-display}


Table: ChIP-Atlas: public Junb ChIP-seq experiments with peaks near Fkbp5 TSS

|result   |
|:--------|
|HTTP 403 |


:::

```{.r .cell-code}
cat("\nPeak Browser URL for manual inspection:\n")
```

::: {.cell-output .cell-output-stdout}

```

Peak Browser URL for manual inspection:
```


:::

```{.r .cell-code}
cat(sprintf(
  "https://chip-atlas.dbcls.jp/peakBrowser/?assemblyId=mm10&factor=JunB&chr=chr4&start=%d&end=%d\n",
  fkbp5_start, fkbp5_end
))
```

::: {.cell-output .cell-output-stdout}

```
https://chip-atlas.dbcls.jp/peakBrowser/?assemblyId=mm10&factor=JunB&chr=chr4&start=99936000&end=100078000
```


:::
:::


### 6.4 Synthesis


::: {.cell}

```{.r .cell-code}
n_promoter <- sum(hits_df$region == "promoter (+-5 kb)")
n_jun      <- sum(grepl("JUN", hits_df$motif_name, ignore.case = TRUE) &
                  hits_df$region %in% c("promoter (+-5 kb)", "gene body"))
fkbp5_row  <- tg |> filter(gene == "Fkbp5")

cat("=== Fkbp5 locus AP-1 evidence summary ===\n")
```

::: {.cell-output .cell-output-stdout}

```
=== Fkbp5 locus AP-1 evidence summary ===
```


:::

```{.r .cell-code}
cat(sprintf("AP-1 hits in promoter (+-5 kb) : %d\n", n_promoter))
```

::: {.cell-output .cell-output-stdout}

```
AP-1 hits in promoter (+-5 kb) : 542
```


:::

```{.r .cell-code}
cat(sprintf("Jun-family hits in promoter+body: %d\n", n_jun))
```

::: {.cell-output .cell-output-stdout}

```
Jun-family hits in promoter+body: 4099
```


:::

```{.r .cell-code}
if (nrow(fkbp5_row) > 0 && !is.na(fkbp5_row$log2FoldChange))
  cat(sprintf("Fkbp5 TRAP-seq: LFC=%.3f, padj=%.3f\n",
              fkbp5_row$log2FoldChange, fkbp5_row$padj))
```

::: {.cell-output .cell-output-stdout}

```
Fkbp5 TRAP-seq: LFC=-1.292, padj=0.010
```


:::

```{.r .cell-code}
cat("\n--- Verdict ---\n")
```

::: {.cell-output .cell-output-stdout}

```

--- Verdict ---
```


:::

```{.r .cell-code}
if (n_jun > 0 && n_promoter > 0) {
  cat("POSITIVE: Jun-family AP-1 motifs present in the Fkbp5 promoter.\n")
  cat("Supports Junb-led cascade: HFD -> Junb up -> Fkbp5 repression ->\n")
  cat("GR de-repression -> Sgk1/Angptl4/Lep up.\n")
  cat("Validate with Junb CUT&RUN in HFD vs CHD adipocytes.\n")
} else if (n_promoter > 0) {
  cat("PARTIAL: AP-1 motifs present but no Jun-family hits in promoter.\n")
  cat("Regulation may be via Junb::Atf3 or Junb::Fos heterodimer.\n")
} else {
  cat("NEGATIVE at 85%: no AP-1 hits in Fkbp5 promoter.\n")
  cat("Consider: relaxing to 80%, checking distal enhancers,\n")
  cat("or indirect regulation via AP-1-activated repressor.\n")
}
```

::: {.cell-output .cell-output-stdout}

```
POSITIVE: Jun-family AP-1 motifs present in the Fkbp5 promoter.
Supports Junb-led cascade: HFD -> Junb up -> Fkbp5 repression ->
GR de-repression -> Sgk1/Angptl4/Lep up.
Validate with Junb CUT&RUN in HFD vs CHD adipocytes.
```


:::
:::


---

## 7. AP-1 + GR composite peak scan

The "composite-enhancer" model predicts that HFD-opened chromatin disproportionately
carries **both AP-1 and GR motifs** — AP-1 pioneers accessibility, licensing
glucocorticoid receptor binding at sites that would otherwise be inaccessible.
We test this by classifying each HFD-specific peak and each shared (background)
peak as AP-1-only, GR-only, both, or neither.

**Motif definitions used:**

- **AP-1 class** — 35 JASPAR 2024 motifs: JUN/JUNB/JUND, FOS/FOSB/FOSL1/FOSL2,
  BATF/BATF3, ATF3, and all pairwise JUN·FOS heterodimer motifs;
  detected via FIMO (p < 1×10⁻⁴) in 500-bp peak windows.
- **GR class** — NR3C1 (MA0113.4), Pgr (MA2323.1), and PGR (MA2327.1);
  the progesterone-receptor motifs share an IR3 half-site biochemically
  indistinguishable from the canonical GR response element.

### 7.1 GR motif presence in HFD-specific peaks


::: {.cell}

```{.r .cell-code}
# AnnotationDbi masks dplyr::select — use explicit namespace throughout
select <- dplyr::select

# GR-class motif columns (NR3C1 + Pgr/PGR as IR3 proxy)
gr_motif_ids <- c("MA0113.4", "MA2323.1", "MA2327.1")

hfd_gr_raw <- read_tsv(
  "results/motif_analysis/composite_scan/HFD_specific/HFD_specific_per_peak_motifs.tsv",
  show_col_types = FALSE
)

gr_cols_present <- intersect(gr_motif_ids, names(hfd_gr_raw))
hfd_gr_classified <- hfd_gr_raw |>
  mutate(has_gr = rowSums(across(all_of(gr_cols_present))) > 0)

n_total  <- nrow(hfd_gr_classified)
n_gr     <- sum(hfd_gr_classified$has_gr)
pct_gr   <- round(100 * n_gr / n_total, 1)

gr_bar_df <- tibble(
  category = factor(c("GR motif present", "No GR motif"),
                    levels = c("No GR motif", "GR motif present")),
  n   = c(n_gr, n_total - n_gr),
  pct = c(pct_gr, 100 - pct_gr)
)

ggplot(gr_bar_df, aes(x = category, y = pct, fill = category)) +
  geom_col(width = 0.55, show.legend = FALSE) +
  geom_text(aes(label = sprintf("%d\n(%.1f%%)", n, pct)),
            vjust = -0.3, size = 3.5) +
  scale_fill_manual(values = c("GR motif present" = "#d62728",
                               "No GR motif"      = "#aec7e8")) +
  scale_y_continuous(limits = c(0, 110), expand = c(0, 0)) +
  labs(
    title    = "GR-class motif presence in HFD-specific peaks",
    subtitle = sprintf("N = %d HFD-specific peaks; GR-class = NR3C1 / Pgr / PGR (JASPAR 2024)",
                       n_total),
    x = NULL, y = "Percentage of peaks (%)"
  ) +
  theme_classic(base_size = 12) +
  theme(axis.text.x = element_text(size = 11))
```

::: {.cell-output-display}
![](figures/rnaseq/gr-presence-panel-1.png){width=1500}
:::
:::


**1526 / 6900** (22.1%) HFD-specific peaks carry a GR-class (NR3C1/Pgr/PGR) motif.

### 7.2 AP-1 + GR composite scan — stacked bar


::: {.cell}

```{.r .cell-code}
# AP-1 motif IDs in JASPAR 2024 (JUN/FOS/BATF core + heterodimers + ATF3)
ap1_ids <- c(
  "MA0099.4", "MA0462.3", "MA0476.2", "MA0477.3", "MA0478.2",
  "MA0488.2", "MA0489.3", "MA0490.3", "MA0491.3", "MA0492.2",
  "MA0605.3", "MA1126.2", "MA1127.1", "MA1128.2", "MA1129.1",
  "MA1130.2", "MA1131.2", "MA1132.2", "MA1133.2", "MA1134.2",
  "MA1135.2", "MA1136.1", "MA1137.2", "MA1138.2", "MA1139.2",
  "MA1140.3", "MA1141.2", "MA1142.2", "MA1143.2", "MA1144.2",
  "MA1145.2", "MA1634.2", "MA0835.3", "MA1951.2", "MA1988.2"
)

# --- HFD-specific peaks: AP-1 from full motif scan ---
hfd_full <- read_tsv(
  "results/motif_analysis/full_motif_scan/HFD_specific/HFD_specific_per_peak_all_motifs.tsv",
  show_col_types = FALSE
)
ap1_cols_hfd <- intersect(ap1_ids, names(hfd_full))
hfd_ap1 <- hfd_full |>
  select(peak, all_of(ap1_cols_hfd)) |>
  mutate(has_ap1 = rowSums(across(all_of(ap1_cols_hfd))) > 0) |>
  select(peak, has_ap1)

hfd_classified <- hfd_ap1 |>
  left_join(hfd_gr_classified |> select(peak, has_gr), by = "peak") |>
  mutate(
    motif_cat = case_when(
      has_ap1 &  has_gr ~ "Both (AP-1 + GR)",
      has_ap1 & !has_gr ~ "AP-1 only",
     !has_ap1 &  has_gr ~ "GR only",
      TRUE              ~ "Neither"
    ),
    peak_set = "HFD-specific\n(n = 6,900)"
  )

# --- Shared peaks: AP-1 from pre-computed FIMO scan ---
shared_ap1_file <- "results/motif_analysis/composite_scan/shared/shared_ap1_per_peak.tsv"

shared_gr_raw <- read_tsv(
  "results/motif_analysis/composite_scan/shared/shared_per_peak_motifs.tsv",
  show_col_types = FALSE
)
gr_cols_shared <- intersect(gr_motif_ids, names(shared_gr_raw))
shared_gr_classified <- shared_gr_raw |>
  mutate(has_gr = rowSums(across(all_of(gr_cols_shared))) > 0)

if (file.exists(shared_ap1_file)) {
  shared_ap1 <- read_tsv(shared_ap1_file, show_col_types = FALSE)
  shared_classified <- shared_ap1 |>
    left_join(shared_gr_classified |> select(peak, has_gr), by = "peak") |>
    mutate(
      motif_cat = case_when(
        has_ap1 &  has_gr ~ "Both (AP-1 + GR)",
        has_ap1 & !has_gr ~ "AP-1 only",
       !has_ap1 &  has_gr ~ "GR only",
        TRUE              ~ "Neither"
      ),
      peak_set = sprintf("Shared\n(n = %s)", format(nrow(shared_gr_classified), big.mark=","))
    )

  # --- Combine and plot ---
  cat_order <- c("Both (AP-1 + GR)", "GR only", "AP-1 only", "Neither")
  cat_colors <- c(
    "Both (AP-1 + GR)" = "#d62728",
    "GR only"          = "#ff7f0e",
    "AP-1 only"        = "#1f77b4",
    "Neither"          = "#d3d3d3"
  )

  all_peaks <- bind_rows(hfd_classified, shared_classified) |>
    count(peak_set, motif_cat) |>
    group_by(peak_set) |>
    mutate(
      pct      = 100 * n / sum(n),
      motif_cat = factor(motif_cat, levels = cat_order)
    ) |>
    ungroup() |>
    mutate(peak_set = factor(peak_set,
                             levels = c("HFD-specific\n(n = 6,900)",
                                        sprintf("Shared\n(n = %s)",
                                                format(nrow(shared_gr_classified), big.mark=",")))))

  # Label only categories ≥ 1%
  label_df <- all_peaks |> filter(pct >= 1)

  ggplot(all_peaks, aes(x = peak_set, y = pct, fill = motif_cat)) +
    geom_col(position = "stack", width = 0.55) +
    geom_text(data = label_df,
              aes(label = sprintf("%.1f%%", pct)),
              position = position_stack(vjust = 0.5),
              size = 3.2, colour = "white", fontface = "bold") +
    scale_fill_manual(values = cat_colors, name = "Motif content") +
    scale_y_continuous(expand = c(0, 0), limits = c(0, 101)) +
    labs(
      title    = "AP-1 + GR composite motif content by peak class",
      subtitle = "FIMO p < 1×10⁻⁴; AP-1 = 35 JUN/FOS/BATF motifs; GR = NR3C1/Pgr/PGR",
      x = NULL, y = "Percentage of peaks (%)"
    ) +
    theme_classic(base_size = 12) +
    theme(legend.position = "right",
          axis.text.x = element_text(size = 11))

} else {
  message("Pre-computed shared AP-1 scan not found at:\n  ", shared_ap1_file,
          "\nRun the FIMO step first (see Section 7 setup notes).")
}
```

::: {.cell-output-display}
![](figures/rnaseq/ap1-gr-stacked-bar-1.png){width=1800}
:::
:::



::: {.cell}

```{.r .cell-code}
# Fisher exact test: enrichment of AP-1+GR co-occurrence in HFD vs shared peaks
if (file.exists(shared_ap1_file) && exists("shared_classified")) {
  hfd_both   <- sum(hfd_classified$motif_cat == "Both (AP-1 + GR)")
  hfd_n      <- nrow(hfd_classified)
  shared_both <- sum(shared_classified$motif_cat == "Both (AP-1 + GR)")
  shared_n    <- nrow(shared_classified)

  tab <- matrix(c(hfd_both,    hfd_n    - hfd_both,
                  shared_both, shared_n - shared_both), nrow = 2)
  ft  <- fisher.test(tab, alternative = "greater")

  cat(sprintf(
    "AP-1 + GR co-occurrence:\n  HFD-specific: %d / %d (%.1f%%)\n  Shared:       %d / %d (%.1f%%)\n  OR = %.2f, p = %.2e\n",
    hfd_both, hfd_n, 100*hfd_both/hfd_n,
    shared_both, shared_n, 100*shared_both/shared_n,
    ft$estimate, ft$p.value
  ))
}
```

::: {.cell-output .cell-output-stdout}

```
AP-1 + GR co-occurrence:
  HFD-specific: 665 / 6900 (9.6%)
  Shared:       4107 / 53397 (7.7%)
  OR = 1.28, p = 2.26e-08
```


:::
:::


---

## 8. Locus-level chromatin at GR-target genes

The GR-sensitisation model makes a testable prediction: genes that are
transcriptionally upregulated in HFD (Sgk1, Angptl4, Lep) should have nearby
HFD-opened ATAC peaks, ideally carrying AP-1 and/or GR motifs. Genes whose
expression does not increase (Pnpla2) should lack this chromatin signature.
Fkbp5 is the inverse case — it is CHD-enriched at both chromatin and RNA levels.



### 8.1 Sgk1 — HFD-opened AP-1+GR composite enhancer


::: {.cell}

```{.r .cell-code}
rna_sgk1 <- tg |> filter(gene == "Sgk1")
sgk1_df  <- make_locus_df("chr10", 21850000, 22080000)
plot_locus(sgk1_df, "Sgk1",
           rna_lfc  = rna_sgk1$log2FoldChange,
           rna_padj = rna_sgk1$padj)
```

::: {.cell-output-display}
![](figures/rnaseq/sgk1-locus-1.png){width=2400}
:::
:::



::: {.cell}

```{.r .cell-code}
sgk1_hfd_peaks <- sgk1_df |> filter(log2FoldChange > 1, !is.na(padj), padj < 0.05)
cat(sprintf("Sgk1 locus HFD-specific peaks (padj<0.05, LFC>1): %d\n",
            nrow(sgk1_hfd_peaks)))
```

::: {.cell-output .cell-output-stdout}

```
Sgk1 locus HFD-specific peaks (padj<0.05, LFC>1): 1
```


:::

```{.r .cell-code}
if (nrow(sgk1_hfd_peaks) > 0)
  cat(sprintf("  chr10:%d-%d  LFC=%.2f  padj=%.3f  motif: %s\n",
              sgk1_hfd_peaks$start, sgk1_hfd_peaks$end,
              sgk1_hfd_peaks$log2FoldChange, sgk1_hfd_peaks$padj,
              sgk1_hfd_peaks$motif_cat))
```

::: {.cell-output .cell-output-stdout}

```
  chr10:21986642-21987014  LFC=1.60  padj=0.008  motif: AP-1 + GR
```


:::
:::


> **chr10:21,986,642–21,987,014** (LFC = +1.60, padj = 0.008) carries **both AP-1
> and GR motifs** — the composite enhancer predicted by the pioneer model.
> Sgk1 is significantly up in HFD TRAP-seq, making this the clearest locus-level
> confirmation of the AP-1 pioneer → GR binding → transcription axis.

### 8.2 Angptl4 — GR target locus


::: {.cell}

```{.r .cell-code}
rna_ang <- tg |> filter(gene == "Angptl4")
ang_df  <- make_locus_df("chr17", 33700000, 33760000)
plot_locus(ang_df, "Angptl4",
           rna_lfc  = rna_ang$log2FoldChange,
           rna_padj = rna_ang$padj)
```

::: {.cell-output-display}
![](figures/rnaseq/angptl4-locus-1.png){width=2100}
:::
:::


> Angptl4 is strongly up in HFD TRAP-seq (LFC ≈ +1.95) but nearby ATAC peaks
> are all CHD-enriched or unchanged. The responsible GR enhancer may lie
> outside the ±30 kb window shown; distal GREs for Angptl4 have been reported
> up to 100 kb upstream in other cell types.

### 8.3 Lep — leptin locus


::: {.cell}

```{.r .cell-code}
rna_lep <- tg |> filter(gene == "Lep")
lep_df  <- make_locus_df("chr6", 28970000, 29050000)
plot_locus(lep_df, "Lep",
           rna_lfc  = rna_lep$log2FoldChange,
           rna_padj = rna_lep$padj)
```

::: {.cell-output-display}
![](figures/rnaseq/lep-locus-1.png){width=2100}
:::
:::


> Lep (leptin) is the most induced transcript in HFD (LFC ≈ +2.01,
> padj = 0.014). No significant ATAC changes within the immediate locus window;
> leptin regulation is known to involve distal fat-specific enhancers.

### 8.4 Pnpla2 — chromatin closes despite GR-target classification


::: {.cell}

```{.r .cell-code}
rna_pnp <- tg |> filter(gene == "Pnpla2")
pnp_df  <- make_locus_df("chr7", 141370000, 141450000)
plot_locus(pnp_df, "Pnpla2",
           rna_lfc  = rna_pnp$log2FoldChange,
           rna_padj = rna_pnp$padj)
```

::: {.cell-output-display}
![](figures/rnaseq/pnpla2-locus-1.png){width=2700}
:::
:::



::: {.cell}

```{.r .cell-code}
pnp_sig <- pnp_df |> filter(!is.na(padj), padj < 0.05)
cat(sprintf("Pnpla2 locus peaks: %d total, %d significant\n",
            nrow(pnp_df), nrow(pnp_sig)))
```

::: {.cell-output .cell-output-stdout}

```
Pnpla2 locus peaks: 12 total, 6 significant
```


:::

```{.r .cell-code}
cat(sprintf("  All significant peaks CHD-enriched: %s\n",
            all(pnp_sig$log2FoldChange < 0)))
```

::: {.cell-output .cell-output-stdout}

```
  All significant peaks CHD-enriched: TRUE
```


:::

```{.r .cell-code}
cat(sprintf("  Significant CHD-up peaks: %d  (none are HFD-up)\n",
            sum(pnp_sig$log2FoldChange < 0)))
```

::: {.cell-output .cell-output-stdout}

```
  Significant CHD-up peaks: 6  (none are HFD-up)
```


:::

```{.r .cell-code}
cat(sprintf("  RNA LFC = %.2f, padj = %.3f\n",
            rna_pnp$log2FoldChange, rna_pnp$padj))
```

::: {.cell-output .cell-output-stdout}

```
  RNA LFC = 0.32, padj = 0.842
```


:::
:::


> **Pnpla2 (ATGL)** shows **6 / 12 significant CHD-enriched peaks** at its
> locus — chromatin closes in HFD — yet the transcript is not significantly
> changed (LFC = +0.32, padj = 0.73). Possible explanations:
>
> 1. **Fkbp5/GR model:** constitutive GR activation (via Fkbp5 loss) could
>    maintain Pnpla2 expression even as local chromatin accessibility declines,
>    through a distal GRE or increased GR nuclear occupancy.
> 2. **Uncoupled regulation:** chromatin changes at the Pnpla2 locus are a
>    consequence of AP-1 remodelling at nearby HFD-specific sites rather than
>    a cause of altered Pnpla2 expression.
> 3. **Compensation:** opposing signals (GR induction vs local chromatin
>    closing) may balance, keeping transcript levels stable.
>
> Pnpla2 is **not chromatin-driven in this dataset**; its classification as
> a GR target rests on the transcriptome rather than ATAC evidence.

---

## 9. BigWig locus tracks (requires server BAM files)

When ATAC-seq and RNA-seq BAM files are available locally, running the Nextflow
pipeline (or the BigWig steps in isolation) will produce:

```
results/bigwig/atac/
  CHD_1.RPGC.bw   CHD_2.RPGC.bw   CHD_3.RPGC.bw
  HFD_1.RPGC.bw   HFD_2.RPGC.bw   HFD_3.RPGC.bw

results/rnaseq/bigwig/
  CHD_1.CPM.bw    CHD_2.CPM.bw    CHD_3.CPM.bw
  HFD_1.CPM.bw    HFD_2.CPM.bw    HFD_3.CPM.bw
```

Place these files in the paths above relative to the project root, then the
chunk below will render IGV-style locus tracks using `rtracklayer`. **The peak-count
bar charts in Sections 6.1a and 8.1–8.4 remain valid and complementary regardless.**


::: {.cell}

```{.r .cell-code}
bw_atac <- list.files("results/bigwig/atac",   pattern="\\.bw$", full.names=TRUE)
bw_rna  <- list.files("results/rnaseq/bigwig", pattern="\\.bw$", full.names=TRUE)

if (length(bw_atac) == 6 && length(bw_rna) == 6) {
  suppressPackageStartupMessages({
    library(rtracklayer)
    library(GenomicRanges)
  })

  # Loci to visualise
  loci_bw <- list(
    Fkbp5   = GRanges("chr4",  IRanges(99900000, 100100000)),
    Sgk1    = GRanges("chr10", IRanges(21850000,  22080000)),
    Angptl4 = GRanges("chr17", IRanges(33700000,  33760000)),
    Lep     = GRanges("chr6",  IRanges(28970000,  29050000)),
    Pnpla2  = GRanges("chr7",  IRanges(141370000, 141450000))
  )

  import_mean <- function(files, cond, roi) {
    mats <- lapply(files[grepl(cond, files)], function(f)
      as.numeric(import(f, which=roi, as="NumericList")[[1]]))
    Reduce("+", mats) / length(mats)
  }

  # Plot one locus (example: Sgk1)
  roi <- loci_bw[["Sgk1"]]
  positions <- seq(start(roi), end(roi))
  chd_cov <- import_mean(bw_atac, "CHD", roi)
  hfd_cov <- import_mean(bw_atac, "HFD", roi)
  cov_df  <- tibble(pos = positions,
                    CHD = chd_cov[seq_along(positions)],
                    HFD = hfd_cov[seq_along(positions)]) |>
    pivot_longer(c(CHD,HFD), names_to="condition", values_to="cov") |>
    mutate(condition = factor(condition, c("CHD","HFD")))

  ggplot(cov_df, aes(x=pos/1e3, y=cov, fill=condition)) +
    geom_area(alpha=0.6, position="identity") +
    scale_fill_manual(values=color_scheme) +
    facet_wrap(~condition, ncol=1) +
    labs(title="Sgk1 locus — ATAC BigWig coverage", x="Position (kb)", y="RPGC") +
    theme_classic(base_size=11) + theme(legend.position="none")
} else {
  message(sprintf(
    "BigWig files not found.\n  ATAC: %d/6 found in results/bigwig/atac/\n  RNA:  %d/6 found in results/rnaseq/bigwig/\nSee README §'AP-1 + GR Composite Peak Scan' for file naming.",
    length(bw_atac), length(bw_rna)
  ))
}
```
:::


---

## Session information


::: {.cell}

```{.r .cell-code}
sessionInfo()
```

::: {.cell-output .cell-output-stdout}

```
R version 4.6.0 (2026-04-24)
Platform: aarch64-apple-darwin23
Running under: macOS Tahoe 26.5

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Detroit
tzcode source: internal

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] httr_1.4.8                               
 [2] TFBSTools_1.50.0                         
 [3] JASPAR2024_0.99.7                        
 [4] BiocFileCache_3.2.0                      
 [5] dbplyr_2.5.2                             
 [6] BSgenome.Mmusculus.UCSC.mm10_1.4.3       
 [7] BSgenome_1.80.0                          
 [8] rtracklayer_1.72.0                       
 [9] BiocIO_1.22.0                            
[10] Biostrings_2.80.0                        
[11] XVector_0.52.0                           
[12] org.Mm.eg.db_3.23.0                      
[13] TxDb.Mmusculus.UCSC.mm10.knownGene_3.10.0
[14] GenomicFeatures_1.64.0                   
[15] AnnotationDbi_1.74.0                     
[16] Biobase_2.72.0                           
[17] ChIPseeker_1.48.0                        
[18] GenomicRanges_1.64.0                     
[19] Seqinfo_1.2.0                            
[20] IRanges_2.46.0                           
[21] S4Vectors_0.50.1                         
[22] BiocGenerics_0.58.1                      
[23] generics_0.1.4                           
[24] ggrepel_0.9.8                            
[25] lubridate_1.9.5                          
[26] forcats_1.0.1                            
[27] stringr_1.6.0                            
[28] dplyr_1.2.1                              
[29] purrr_1.2.2                              
[30] readr_2.2.0                              
[31] tidyr_1.3.2                              
[32] tibble_3.3.1                             
[33] ggplot2_4.0.3                            
[34] tidyverse_2.0.0                          

loaded via a namespace (and not attached):
  [1] JASPAR2020_0.99.10                      
  [2] RColorBrewer_1.1-3                      
  [3] rstudioapi_0.18.0                       
  [4] jsonlite_2.0.0                          
  [5] tidydr_0.0.6                            
  [6] magrittr_2.0.5                          
  [7] ggtangle_0.1.2                          
  [8] farver_2.1.2                            
  [9] rmarkdown_2.31                          
 [10] fs_2.1.0                                
 [11] vctrs_0.7.3                             
 [12] memoise_2.0.1                           
 [13] Rsamtools_2.28.0                        
 [14] RCurl_1.98-1.18                         
 [15] ggtree_4.2.0                            
 [16] htmltools_0.5.9                         
 [17] S4Arrays_1.12.0                         
 [18] TxDb.Hsapiens.UCSC.hg19.knownGene_3.22.1
 [19] plotrix_3.8-14                          
 [20] curl_7.1.0                              
 [21] SparseArray_1.12.2                      
 [22] gridGraphics_0.5-1                      
 [23] KernSmooth_2.23-26                      
 [24] htmlwidgets_1.6.4                       
 [25] httr2_1.2.2                             
 [26] plyr_1.8.9                              
 [27] cachem_1.1.0                            
 [28] GenomicAlignments_1.48.0                
 [29] igraph_2.3.1                            
 [30] lifecycle_1.0.5                         
 [31] pkgconfig_2.0.3                         
 [32] Matrix_1.7-5                            
 [33] R6_2.6.1                                
 [34] fastmap_1.2.0                           
 [35] MatrixGenerics_1.24.0                   
 [36] digest_0.6.39                           
 [37] aplot_0.2.9                             
 [38] enrichplot_1.32.0                       
 [39] TFMPvalue_1.0.0                         
 [40] ggnewscale_0.5.2                        
 [41] patchwork_1.3.2                         
 [42] RSQLite_3.53.1                          
 [43] seqLogo_1.78.0                          
 [44] filelock_1.0.3                          
 [45] labeling_0.4.3                          
 [46] timechange_0.4.0                        
 [47] polyclip_1.10-7                         
 [48] abind_1.4-8                             
 [49] compiler_4.6.0                          
 [50] bit64_4.8.2                             
 [51] fontquiver_0.2.1                        
 [52] withr_3.0.2                             
 [53] S7_0.2.2                                
 [54] BiocParallel_1.46.0                     
 [55] DBI_1.3.0                               
 [56] gplots_3.3.0                            
 [57] ggforce_0.5.0                           
 [58] MASS_7.3-65                             
 [59] rappdirs_0.3.4                          
 [60] DelayedArray_0.38.1                     
 [61] rjson_0.2.23                            
 [62] caTools_1.18.3                          
 [63] gtools_3.9.5                            
 [64] tools_4.6.0                             
 [65] otel_0.2.0                              
 [66] scatterpie_0.2.6                        
 [67] ape_5.8-1                               
 [68] glue_1.8.1                              
 [69] restfulr_0.0.16                         
 [70] nlme_3.1-169                            
 [71] GOSemSim_2.38.0                         
 [72] grid_4.6.0                              
 [73] cluster_2.1.8.2                         
 [74] reshape2_1.4.5                          
 [75] gtable_0.3.6                            
 [76] tzdb_0.5.0                              
 [77] hms_1.1.4                               
 [78] pillar_1.11.1                           
 [79] yulab.utils_0.2.4                       
 [80] vroom_1.7.1                             
 [81] tweenr_2.0.3                            
 [82] treeio_1.36.1                           
 [83] lattice_0.22-9                          
 [84] bit_4.6.0                               
 [85] DirichletMultinomial_1.54.0             
 [86] tidyselect_1.2.1                        
 [87] fontLiberation_0.1.0                    
 [88] GO.db_3.23.1                            
 [89] knitr_1.51                              
 [90] fontBitstreamVera_0.1.1                 
 [91] SummarizedExperiment_1.42.0             
 [92] xfun_0.57                               
 [93] matrixStats_1.5.0                       
 [94] stringi_1.8.7                           
 [95] UCSC.utils_1.8.0                        
 [96] lazyeval_0.2.3                          
 [97] ggfun_0.2.0                             
 [98] yaml_2.3.12                             
 [99] boot_1.3-32                             
[100] evaluate_1.0.5                          
[101] codetools_0.2-20                        
[102] cigarillo_1.2.0                         
[103] gdtools_0.5.1                           
[104] ggplotify_0.1.3                         
[105] cli_3.6.6                               
[106] systemfonts_1.3.2                       
[107] Rcpp_1.1.1-1.1                          
[108] GenomeInfoDb_1.48.0                     
[109] png_0.1-9                               
[110] XML_3.99-0.23                           
[111] parallel_4.6.0                          
[112] blob_1.3.0                              
[113] DOSE_4.6.0                              
[114] bitops_1.0-9                            
[115] pwalign_1.8.0                           
[116] tidytree_0.4.7                          
[117] ggiraph_0.9.6                           
[118] enrichit_0.1.4                          
[119] scales_1.4.0                            
[120] crayon_1.5.3                            
[121] rlang_1.2.0                             
[122] KEGGREST_1.52.0                         
```


:::
:::

