---
title: "Insulin Tolerance Tests Controlling for Lean Mass"
author: "Laura Gunder and Dave Bridges"
date: "March 23, 2019"
output:
  html_document:
    highlight: tango
    keep_md: yes
    number_sections: no
    toc: yes
  pdf_document:
    highlight: tango
    keep_tex: yes
    number_sections: no
    toc: yes
---


```{r global_options, include=FALSE}
library(knitr)
#figures makde will go to directory called figures, will make them as both png and pdf files 
opts_chunk$set(fig.path='figures/',
               echo=FALSE, warning=FALSE, message=FALSE,dev=c('png','pdf'))
options(scipen = 2, digits = 3)
# set echo and message to TRUE if you want to display code blocks and code output respectively

knitr::knit_hooks$set(inline = function(x) {
  knitr:::format_sci(x, 'md')
})


superpose.eb <- function (x, y, ebl, ebu = ebl, length = 0.08, ...)
  arrows(x, y + ebu, x, y - ebl, angle = 90, code = 3,
  length = length, ...)

  
se <- function(x) sd(x, na.rm=T)/sqrt(length(x))

#load these packages, nearly always needed
library(tidyr)
library(dplyr)

# sets maize and blue color scheme
color.scheme <- c('#00274c', '#ffcb05')
```

```{r ITT-data}
library(readr)
input.data <- '../../data/raw/Muscle Study ITT.csv'

library(forcats)
itt.data<-read_csv(input.data,
                   col_types = cols(
                     ID = col_factor(levels = NULL),
                     diet = col_factor(levels = NULL),
                     treatment = col_factor(levels = NULL),
                     ID = col_factor(levels = NULL),
                     time = col_factor(levels = NULL),
                     glucose = col_double())) %>%
  rename('Treatment'='treatment') %>%
  mutate(Treatment = fct_recode(Treatment,'Water'='water',"Dexamethasone"='dexamethasone')) #capitalized dexamethasone and water

#knitr::kable(itt.data %>% select(ID, treatment, diet))%>%distinct_()
```

```{r summary}
color.scheme <- c('black','red')
itt.summary<-itt.data %>%
  group_by(Treatment, diet, time)%>%
  summarize(Mean= mean(glucose),
            Error = se(glucose)) %>%
  na.omit
```

# Insulin Tolerance Test

## Raw Values

```{r itt-raw}
library(ggplot2)
  #Raw values
library(forcats)
itt.summary %>%
  mutate(Diet = fct_recode(diet, "Lean"="NCD","Obese"="HFD")) %>%
  ggplot(aes(y=Mean,
           x=time,
           ymin = Mean-Error,
          ymax = Mean+Error,
          group = Treatment,
         color=Treatment)) +
  geom_point(size=3) +
  geom_errorbar(width=0.5) +
  geom_line() +
  facet_grid(.~Diet)+
  scale_color_grey(name="Treatment") +
  expand_limits(y=0,x=6) +
  labs(x='Insulin (Minutes)',
       y='Blood Glucose (mg/dL)') +
  theme_classic() +
  theme(text=element_text(size=18),
        legend.position=c(0.15,0.75),
        legend.text=element_text(size=12)) 


itt.summary %>%
  ggplot(aes(y=Mean,
           x=time,
           ymin = Mean-Error,
          ymax = Mean+Error,
          group = Treatment,
          col=Treatment)) +
    geom_point()+
    geom_line()+
    facet_grid(.~diet)+
    geom_errorbar(width = 0.2)+
    scale_colour_manual(values=color.scheme)+
    labs(y="Blood Glucose (mg/dL)", x= "Insulin (minutes)")+
    ggtitle("")+
    expand_limits(y=0) +
    theme_classic() +
    theme(legend.position = c(0.25,0.75))
```

### ITT Statistics (Raw Values)

```{r itt-raw-stats}
library(lme4)
library(broom)
library(lmerTest)
glucose.null.lme.ncd <- lmer(glucose ~ as.factor(time)  + (1|ID), data = itt.data %>% filter(diet=='NCD'))
glucose.trt.lme.ncd <- lmer(glucose ~ as.factor(time)  * Treatment + (1|ID), data = itt.data %>% filter(diet=='NCD'))

kable(tidy(anova(glucose.trt.lme.ncd, glucose.null.lme.ncd)), caption = "Chi squared test for effects of dexamethasone on NCD for absolute values", digits = 15)
glucose.trt.lme.ncd %>% anova %>% kable(caption="ANOVA table for NCD absolute values", digits = 15)

glucose.null.lme.hfd <- lmer(glucose ~ as.factor(time)  + (1|ID), data = itt.data %>% filter(diet=='HFD'))
glucose.trt.lme.hfd <- lmer(glucose ~ as.factor(time)  * Treatment + (1|ID), data = itt.data %>% filter(diet=='HFD'))

kable(tidy(anova(glucose.trt.lme.hfd, glucose.null.lme.hfd)), caption = "Chi squared test for effects of dexamethasone on HFD for absolute values", digits = 15)
glucose.trt.lme.hfd %>% anova %>% kable(caption="ANOVA table for HFD absolute values", digits = 15)
```

### ITT Slope Calculations

Using only the first 45 minutes to see initial insulin sensitivity

```{r itt-initial}
itt.rates <-
  itt.data %>%
  mutate(time = as.integer(as.character(time))) %>%
  filter(time<=30) %>%
  group_by(ID, Treatment,diet) %>%
  summarize(Rate = lm(glucose~time)$coef %>% nth(2))

itt.rates %>%
  group_by(diet, Treatment)%>%
  select(Rate)%>%
  summarise_all(.funs = funs(mean, se)) %>%
  ggplot(aes(Treatment,
                         mean,
                         ymax = mean + se,
                         ymin = mean - se, fill = Treatment))+
  facet_grid(.~diet)+
  geom_col(stat = "identity", aes(fill = Treatment))+
  geom_errorbar(width = 0.2)+
  scale_fill_manual(values=c('black','red'))+
  theme_classic()+
  labs(x="Treatment",y="Rate of Change in Blood Glucose (mg/dL)",
       subtitle="First 45 mins")
```

## Normalized Values
  
```{r itt-normalized}  
  #normalized values
  itt.data.normalized <- 
    itt.data%>%
    group_by(ID) %>%
    mutate(norm.glucose = glucose/glucose[time==0]*100)
  
  itt.summary.norm <-
  itt.data.normalized %>%
    group_by(Treatment, diet, time)%>%
  summarize(Mean= mean(norm.glucose),
            Error = se(norm.glucose)) %>%
    na.omit
  
    ggplot(itt.summary.norm, aes(y=Mean,
           x=time,
           ymin = Mean-Error,
          ymax = Mean+Error,
          group = Treatment)) +
    geom_point(aes(col=Treatment))+
    geom_line(aes(col=Treatment))+
    facet_grid(.~diet)+
    geom_errorbar(aes(col=Treatment), width = 0.2)+
    scale_colour_manual(values=color.scheme)+
    labs(y="blood glucose (mg/dL)", x= "time (minutes)")+
    ggtitle("Blood glucose following insulin administration")+
    theme_classic()  
```    
    
 
# Fasting Blood Glucose

```{r fasting-blood-glucose}
fasting.data<- itt.data%>%
  filter(time == 0)%>%
  group_by(diet, Treatment)%>%
  select(glucose)%>%
  summarise_all(.funs = funs(mean, se))

ggplot(fasting.data, aes(diet,
                         mean,
                         ymax = mean + se,
                         ymin = mean - se, fill = Treatment))+
  geom_bar(stat='identity', position='dodge', width=0.75) +
  geom_errorbar(position=position_dodge(width=0.75),aes(group=Treatment), width=0.5) +
  theme_classic()+
  labs(x="",y="Blood Glucose (mg/dL)")+
  ggtitle("Fasting Blood Glucose") +
  expand_limits(y=0) +
  scale_fill_grey() +
  scale_x_discrete(labels=c("Lean","Obese")) +
  theme_classic() +
  theme(text=element_text(size=18),
        legend.position=c(0.15,0.75),
        legend.text=element_text(size=12)) 

library(broom)
aov(`glucose` ~ diet * Treatment, data = itt.data) %>% tidy %>% kable(caption="ANOVA of FBG")
```

```{r statistics}
library(lme4)
library(broom)
library(car)
#shapiro test for normal distribution
##for pregnant animals
filter(itt.data, diet=="NCD"&Treatment=="Water")$glucose %>% shapiro.test #normal
filter(itt.data, diet=="NCD"&Treatment=="Dexamethasone")$glucose %>% shapiro.test#normal
filter(itt.data, diet=="HFD")$glucose %>% shapiro.test #not normal

#ggplot(filter(itt.data, diet=="HFD"), aes(glucose))+geom_histogram()#right skew to the data
wilcox.test(glucose~diet,data= itt.data)#THIS ONE FOR stats


#testing for equal variance
leveneTest(glucose~diet,data= itt.data, var.equal = FALSE)$"Pr(>F)"[1]#not equal variance, use Welch's t test (var.equal = FALSE)

#mixed linear modeling 
glucose.lme <- lmer(glucose~time + Treatment + diet + time:Treatment + Treatment:diet + (1|ID), data=itt.data)

glucose.null.lme <- lmer(glucose ~ time  + (1|ID), data = itt.data %>% filter(Treatment=='Water'))
glucose.diet.lme <- lmer(glucose ~ time  * diet + (1|ID), data = itt.data %>% filter(Treatment=='Water'))


kable(tidy(anova(glucose.diet.lme, glucose.null.lme)), caption = "ANOVA")


#for normalized data

glucose.null.lme <- lmer(glucose ~ time  + (1|ID), data = itt.data.normalized %>% filter(diet=='NCD'))
glucose.trt.lme <- lmer(glucose ~ time  * Treatment + (1|ID), data = itt.data.normalized %>% filter(diet=='NCD'))

kable(tidy(anova(glucose.trt.lme, glucose.null.lme)), caption = "Chi squared test for effects of dexamethasone on NCD for normalized values")

glucose.null.lme <- lmer(glucose ~ time  + (1|ID), data = itt.data.normalized %>% filter(diet=='HFD'))
glucose.trt.lme <- lmer(glucose ~ time  * Treatment + (1|ID), data = itt.data.normalized %>% filter(diet=='HFD'))

kable(tidy(anova(glucose.trt.lme, glucose.null.lme)), caption = "Chi squared test for effects of dexamethasone on HFD for normalized values")

sigma(glucose.diet.lme)#gives the value of the standard deviation for the fixed effects model ofject specified
glucose.null.lme.n <- lmer(norm.glucose ~ time  + (1|ID), data = itt.data.normalized %>% filter(Treatment=='Water'))
glucose.diet.lme.n <- lmer(norm.glucose ~ time  * diet + (1|ID), data = itt.data.normalized %>% filter(Treatment=='Water'))

kable(tidy(anova(glucose.diet.lme.n, glucose.null.lme.n)), caption = "ANOVA for normalized data")

#fasting blood glucose
filter(itt.data, diet =="NCD"&Treatment=="Water"&time==0)$glucose%>%shapiro.test#normal
filter(itt.data, diet=="HFD"&time==0)$glucose%>%shapiro.test#normal
leveneTest(glucose~diet,data= itt.data, var.equal = FALSE)$"Pr(>F)"[1]#use Welch's non-equal variance
```