---
title: "Analysis of iWAT mRNA Transcripts"
author: "Innocence Harvey and Dave Bridges"
date: "February 25, 2015"
output:
  html_document:
    keep_md: yes
  pdf_document:
    keep_tex: yes
---

```{r global_options, include=FALSE}
library(knitr)
opts_chunk$set(fig.path='figures/',
               echo=FALSE, warning=FALSE, message=FALSE,dev=c('png','pdf'))
```

# Data Entry


```{r data-entry}
data_file <- '../..//data/raw/iWAT qPCR Summary.csv'
data <- read.csv(data_file)
#set the treatment
data$Treatment <- relevel(data$Treatment, ref='Water')
```

Data was read from the file `r data_file`.  These data were most recently updated on `r date()`.

#Analysis

```{r analysis}
library(dplyr)
qpcr.summary <- 
  data %>%
  group_by(Gene,Treatment) %>%
  summarise(mean = mean(Normalized.Expression),
            se = sd(Normalized.Expression)/sqrt(length(Normalized.Expression)),
            n = length(Normalized.Expression),
            shapiro = shapiro.test(Normalized.Expression)$p.value) %>%
  mutate(norm.mean = mean/mean[1],
         norm.se = se/mean[1])
```

```{r statistics, results='asis'}
library(car)
stats.summary <- data.frame()
for (gene in levels(data$Gene)) {
  stats.summary[gene,'shapiro-water'] <- with(subset(data, Gene==gene&Treatment=='Water'), shapiro.test(Normalized.Expression))$p.value
  stats.summary[gene,'shapiro-dex'] <- with(subset(data, Gene==gene&Treatment=='Dexamethasone'), shapiro.test(Normalized.Expression))$p.value
  stats.summary[gene, 'levene'] <- leveneTest(Normalized.Expression~Treatment, data=subset(data,Gene==gene))$"Pr(>F)"[1]
}

#decision tree for the test
for (gene in levels(data$Gene)){
  if (stats.summary[gene,c('shapiro-water','shapiro-dex')] < 0.05) {
    stats.summary[gene,'Test'] <- 'Wilcoxon'
  }
  else
    if (stats.summary[gene,'levene'] < 0.05) {
      stats.summary[gene,'Test'] <- 'Welchs'
    }
  else
    stats.summary[gene,'Test'] <- 'Student'
}

#calculate appropriate p-value
for (gene in levels(data$Gene)) {
  if (stats.summary[gene,'Test'] == "Student") {
    stats.summary[gene,'pval'] <- t.test(Normalized.Expression~Treatment, data=subset(data,Gene==gene), var.equal=T)$p.value
  }
  else
    if (stats.summary[gene,'Test'] == 'Welchs') {
      stats.summary[gene,'pval'] <- t.test(Normalized.Expression~Treatment, data=subset(data,Gene==gene), var.equal=F)$p.value
  }
  else
    if (stats.summary[gene,'Test'] == 'Wilcoxon'){
     stats.summary[gene,'pval'] <- wilcox.test(Normalized.Expression~Treatment, data=subset(data,Gene==gene))$p.value 
    }
  }

stats.summary$padj <- p.adjust(stats.summary$pval, method="BH")
stats.summary$Significant <- stats.summary$padj < 0.05
library(xtable)
print(xtable(stats.summary, caption='Pairwise statistics summary, p-values adjusted by BH', digits=3), type='html')
```

## Lipogenic Genes

```{r iwat-lipogenic-genes}
genes <- c('Acaca','Acsl1','Acss2','Agpat2','Dgat2','Fasn','Gpam','Gpd1','Scd1','Dhcr7','Dhcr24')
library(reshape2)
ymax <- with(subset(qpcr.summary, Gene %in% genes), max(norm.mean) + max (norm.se))
plot <- barplot(as.matrix(dcast(subset(qpcr.summary, Gene %in% genes), Treatment~Gene, value.var='norm.mean')[2:(length(genes)+1)]), 
        beside=T, las=2, ylim=c(0,ymax), ylab="Relative Expression")

superpose.eb <- 
 function (x, y, ebl, ebu = ebl, length = 0.08, ...) 
 arrows(x, y + ebu, x, y - ebl, angle = 90, code = 3, 
 length = length, ...)

superpose.eb(plot,
             as.matrix(dcast(subset(qpcr.summary, Gene %in% genes), Treatment~Gene, value.var='norm.mean')[2:(length(genes)+1)]),
             as.matrix(dcast(subset(qpcr.summary, Gene %in% genes), Treatment~Gene, value.var='norm.se')[2:(length(genes)+1)]))
legend('topleft', levels(data$Treatment), bty='n', fill=grey.colors(2))
```

# Proteasome Genes

```{r iwat-proteosome-genes}
genes <- c('Psmd1','Psmd8')
ymax <- with(subset(qpcr.summary, Gene %in% genes), max(norm.mean) + max (norm.se))
plot <- barplot(as.matrix(dcast(subset(qpcr.summary, Gene %in% genes), Treatment~Gene, value.var='norm.mean')[2:(length(genes)+1)]), 
        beside=T, las=2, ylim=c(0,ymax), ylab="Relative Expression")

superpose.eb(plot,
             as.matrix(dcast(subset(qpcr.summary, Gene %in% genes), Treatment~Gene, value.var='norm.mean')[2:(length(genes)+1)]),
             as.matrix(dcast(subset(qpcr.summary, Gene %in% genes), Treatment~Gene, value.var='norm.se')[2:(length(genes)+1)]))
legend('topleft', levels(data$Treatment), bty='n', fill=grey.colors(2))
```

# TCA Cycle Genes
```{r iwat-tca-genes}
genes <- c('Aco1','Idh1','Ldhb','Mdh1','Me1')
ymax <- with(subset(qpcr.summary, Gene %in% genes), max(norm.mean) + max (norm.se))
plot <- barplot(as.matrix(dcast(subset(qpcr.summary, Gene %in% genes), Treatment~Gene, value.var='norm.mean')[2:(length(genes)+1)]), 
        beside=T, las=2, ylim=c(0,ymax), ylab="Relative Expression")

superpose.eb(plot,
             as.matrix(dcast(subset(qpcr.summary, Gene %in% genes), Treatment~Gene, value.var='norm.mean')[2:(length(genes)+1)]),
             as.matrix(dcast(subset(qpcr.summary, Gene %in% genes), Treatment~Gene, value.var='norm.se')[2:(length(genes)+1)]))
legend('topleft', levels(data$Treatment), bty='n', fill=grey.colors(2))
```

# Glucocorticoid Receptor
```{r iwat-glucocorticoid-receptor}
genes <- c('Nr3c1')
ymax <- with(subset(qpcr.summary, Gene %in% genes), max(norm.mean) + max (norm.se))
plot <- barplot(subset(qpcr.summary, Gene %in% genes)$norm.mean,
        las=1, ylim=c(0,ymax), ylab="Relative Expression", names.arg=levels(data$Treatment), col=grey.colors(2))

superpose.eb(plot,
             subset(qpcr.summary, Gene %in% genes)$norm.mean,
             subset(qpcr.summary, Gene %in% genes)$norm.se)
legend('topleft', levels(data$Treatment), bty='n', fill=grey.colors(2))
```

# Session Information
```{r sessionInfo}
sessionInfo()
```