Barplot Analysis of Acromegaly Results
=======================================

Used Analysed DESeq results.

```{r file-input, echo=FALSE, warning=FALSE}
filename <- "../data/processed/RPKM_counts_Acromegaly_GRCh37.74.csv"
deseq.filename <- "../data/processed/Annotated Results GRCh37.74 - Acromegaly.csv"
#read in the file
normalized.data <- read.csv(filename, row.names='X')
deseq.data <- read.csv(deseq.filename, row.names='X')
sample_mapping <- read.csv("../data/raw/patient_sample_mapping.csv")
patient_info <- read.csv("../data/raw/patient_table.csv")
mapping <- merge(sample_mapping, patient_info, by.x="patient..", by.y="id")
mapping$samplename <- paste("sample", mapping$sample.., sep="")
mapping$group <- relevel(mapping$group, ref="non-functioning")
levels(mapping$group)[levels(mapping$group)=="non-functioning"] <- "Control"
levels(mapping$group)[levels(mapping$group)=="Cushing's"] <- "Cushing's"
levels(mapping$group)[levels(mapping$group)=="acromegaly"] <- "Acromegaly"
mapping$age.cat <- cut(mapping$age, breaks=c(0,40,60,100))
mapping$age.cat <- ifelse(mapping$age.cat=="(40,60]", "Young", "Old")

filtered.mapping <- mapping[mapping$patient.. != 29,]
filtered.normalized.data <- normalized.data[,colnames(normalized.data ) != mapping[mapping$patient.. == 29,]$samplename]
filtered.mapping.acro <- filtered.mapping[filtered.mapping$group!="Cushing's",]
filtered.mapping.acro <- filtered.mapping.acro[order(filtered.mapping.acro$group),]
filtered.normalized.acro <- filtered.normalized.data[,filtered.mapping.acro$samplename]
#colnames(filtered.normalized.acro) <- filtered.mapping.acro$group


#get gene names for transcripts
library(biomaRt)
ensembl = useMart("ensembl", dataset="hsapiens_gene_ensembl")
gene.data <- getBM(attributes=c('ensembl_gene_id', 'hgnc_symbol'),
                   filters = 'ensembl_gene_id', values = rownames(filtered.normalized.data), mart = ensembl)
rpkm.data <- merge(filtered.normalized.acro, gene.data, by.x='row.names', by.y='ensembl_gene_id') 
rpkm.data.unique <- rpkm.data[!duplicated(rpkm.data$hgnc_symbol),]

rownames(rpkm.data.unique) <- rpkm.data.unique$hgnc_symbol
rpkm.data.unique <- rpkm.data.unique[,-1]
library(reshape2) 
rpkm.long <- reshape(rpkm.data.unique, direction="long", varying=list(names(rpkm.data.unique)[1:18]), v.names="Expression", idvar="hgnc_symbol", ids=rownames(rpkm.data.unique), timevar="Disease",  times=c(rep('Control',11),rep('Acromegaly',7)))
rpkm.age <- reshape(rpkm.data.unique, direction="long", varying=list(names(rpkm.data.unique)[1:18]), v.names="Expression", idvar="hgnc_symbol", ids=rownames(rpkm.data.unique), timevar="Age",  times=filtered.mapping.acro$age.cat)
rpkm.long$Age <- rpkm.age$Age


genes.of.interest <- c("IGF1", "IGFBP3", "IGFBP5","IGFALS","CISH", "SOCS2", "ADRB3", "TSHR", "TCF7L2", "PYGM","HSD11B1","LPL","PGM3","NR3C1","MVP", "SCD", "APOL4", "PTPN3", "PTPN4","CCNE1","CCNG1", "CDKN2B", "CDKN2B-AS1", "NAP1L1","ORC2", "PDGFD", "RARB","PGRMC1","SCDP1","SCP2", "MAP3K5","MAPK13","MAPKAPK3","MATN2","MFAP4","MMRN2", "NRIP1","MMD","ABHD5","LEPR","ACVR1C","GFPT1","CYB5A","AVPR1A","PTGER3","FADS2","LIPE","PNPLA2", "MGLL","AKT1", "AKT2","AKT3", "INSR", "IRS1", "IRS2", "IRS4", "SLC2A4", "PIK3R1","BAG4","CAPN6","G0S2","PPARG", "PPARA","SERPINA6")
young.sig.genes <- read.csv("../data/processed/Acro_vs_Control_Young_Sig_Genes.csv")
young.sig.genes <- young.sig.genes[-1,-1]
young.sig.genes <- as.character(young.sig.genes)

old.sig.genes <- c("CPXM1", "SCD", "FADS2", "IGSF10")


#calculate standard error
library(plyr)

rpkm.long.cal <- ddply(rpkm.long, .(hgnc_symbol,Disease,Age), summarise, se = sd(Expression, na.rm=T)/sqrt(length(Expression)), mean_Expression = mean(Expression, na.rm=T))

rpkm.long.cal$Disease <- factor(rpkm.long.cal$Disease)
rpkm.long.cal$Disease <- factor(rpkm.long.cal$Disease, levels=rev(levels(rpkm.long.cal$Disease)))
rpkm.long.cal$Age <- factor(rpkm.long.cal$Age)
rpkm.long.cal$Age <- factor(rpkm.long.cal$Age, levels=rev(levels(rpkm.long.cal$Age)))

rpkm.long.cal <- rpkm.long.cal[order(rev(rpkm.long.cal$hgnc_symbol), rev(rpkm.long.cal$Disease), decreasing=T),]

goi.long.cal <- rpkm.long.cal[rpkm.long.cal$hgnc_symbol%in%genes.of.interest,]
colnames(goi.long.cal)[1] <- "Genes"
goi.long.cal <- goi.long.cal[goi.long.cal$Genes!='NA',]
goi.long.cal <- goi.long.cal[goi.long.cal$Genes!='NA.1',]
goi.long.cal <- goi.long.cal[order(rev(goi.long.cal$Genes), goi.long.cal$Disease, decreasing=T),]

young.long.cal <- rpkm.long.cal[rpkm.long.cal$hgnc_symbol%in%young.sig.genes,]
#young.long.cal <- young.long.cal[young.long.cal$hgnc_symbol!='NA',]
#young.long.cal <- young.long.cal[young.long.cal$hgnc_symbol!='NA.1',]

```

```{r barplots, dev=c('png','pdf'), echo=FALSE, fig.show='asis', warning=FALSE}
library(reshape2)
library(ggplot2)
gene="IGF1"
for (gene in genes.of.interest) {
  #pdf(sprintf('../figures/%s-barplot.pdf', gene))
  
  gene.data <- goi.long.cal[goi.long.cal$Genes==gene,]
    #pdf(paste('../figures/',gene,'-barplot.pdf',sep=""))
  ggplot(gene.data, aes(x=Age,y=mean_Expression,fill=Disease)) + 
    geom_bar(stat="identity", position="dodge", colour="black") + 
    geom_errorbar(aes(ymin=mean_Expression-se, ymax=mean_Expression+se), position=position_dodge(0.9), width=.2) + 
    xlab("") + ylab("mRNA Expression (RPKM)")+ 
    theme_bw() + ggtitle(gene) + 
    theme(panel.grid.minor = element_blank()) + 
    theme(panel.grid.major = element_blank()) + 
    theme(panel.border=element_blank()) + 
      #scale_x_discrete(labels=gene.data$Disease) + 
    theme(axis.line = element_line(color = 'black')) +
    scale_colour_grey(start = 0.5, end = .9)
  ggsave(filename=paste('../Figures/Acro_Age/Acro-Age-',gene,'-barplot.pdf',sep=""))
}

for (gene in young.sig.genes) {
  #pdf(sprintf('../figures/%s-barplot.pdf', gene))
  #print(gene)
  if((gene!='FLJ27365') & (gene!='RP11-407P15.2'))
  {
    gene.data <- young.long.cal[young.long.cal$hgnc_symbol==gene,]
    ggplot(gene.data, aes(x=Age,y=mean_Expression,fill=Disease)) + 
      geom_bar(stat="identity", position="dodge", colour="black") + 
      geom_errorbar(aes(ymin=mean_Expression-se, ymax=mean_Expression+se), position=position_dodge(0.9), width=.2) + 
      xlab("") + ylab("mRNA Expression (RPKM)")+ 
      theme_bw() + ggtitle(gene) + 
      theme(panel.grid.minor = element_blank()) + 
      theme(panel.grid.major = element_blank()) + 
      theme(panel.border=element_blank()) + 
      theme(axis.line = element_line(color = 'black')) +
      scale_colour_grey(start = 0.5, end = .9)
      
    ggsave(filename=paste('../Figures/Acro_Age/Acro-Young-',gene,'-barplot.pdf',sep=""))
    
  }
}

for (gene in old.sig.genes) {
  #pdf(sprintf('../figures/%s-barplot.pdf', gene))
  gene.data <- rpkm.long.cal[rpkm.long.cal$hgnc_symbol==gene,]
  #pdf(paste('../figures/',gene,'-barplot.pdf',sep=""))
  ggplot(gene.data, aes(x=Age,y=mean_Expression,fill=Disease)) + 
    geom_bar(stat="identity", position="dodge", colour="black") + 
    geom_errorbar(aes(ymin=mean_Expression-se, ymax=mean_Expression+se), position=position_dodge(0.9), width=.2) + 
    xlab("") + ylab("mRNA Expression (RPKM)")+ 
    theme_bw() + ggtitle(gene) + 
    theme(panel.grid.minor = element_blank()) + 
    theme(panel.grid.major = element_blank()) + 
    theme(panel.border=element_blank()) + 
    #scale_x_discrete(labels=gene.data$Disease) + 
    theme(axis.line = element_line(color = 'black'))+
    scale_colour_grey(start = 0.5, end = .9)
  ggsave(filename=paste('../Figures/Acro_Age/Acro-Old-',gene,'-barplot.pdf',sep=""))
}

```

```{r lipase-barplots, dev=c('png','pdf'), echo=FALSE, fig.show='asis',  warning=FALSE}
#missing lipb, fix showing acro/control
lipases <- c("LPL","PNPLA2", "MGLL","LIPE", "LIPA", "LIPC", "PNLIP","LIPG","CEL","LIPF","LIPH", "DAGLB","DAGLA", "LIPI","LIPN","LIPM","LIPK","LIPJ")

#lipase.data <- getBM(attributes=c('ensembl_gene_id', 'hgnc_symbol'),
 #                  filters = 'hgnc_symbol', values = lipases, mart = ensembl)
lipase.cal <- rpkm.long.cal[rpkm.long.cal$hgnc_symbol%in%lipases,]
colnames(lipase.cal)[1] <- "Genes"

#qplot(data=lipase.cal, x=Genes, y=mean_Expression, geom="bar", fill=Disease, position="dodge", stat="identity")
library(ggplot2)
ggplot(lipase.cal, aes(x=Genes, y=mean_Expression, fill=Disease))+ 
    geom_bar(stat="identity",width=.8, position=position_dodge(width=.8), col="black", show_guide=F) + 
    geom_errorbar(position=position_dodge(width=.8), aes(ymin=mean_Expression-se, ymax=mean_Expression+se), width=.2)+ 
    facet_grid(Age ~ .) +
    theme_bw()+theme(axis.text.x=element_text(angle=90))+xlab("")+ ylab("mRNA Expression (RPKM)") +
    theme(panel.grid.minor = element_blank()) + theme(panel.grid.major = element_blank()) + 
    theme(panel.border=element_blank())+ 
    theme(axis.line = element_line(color = 'black')) +
    scale_fill_grey(start = 0.3, end = .9) +
    #guides(fill = guide_legend(keywidth = .5, keyheight = .5)) +
    theme(text = element_text(size=20), axis.text.x = element_text(angle=70,hjust=.5,vjust=.5)) +
    theme(legend.position=c(.60,.90))

ggsave("../Figures/Acro_Age/Acro-Age-adjusted-all-lipases-RPKM.pdf")

```

```{r draw lipase genes, echo=FALSE, fig.show='asis',  warning=FALSE}
#draw each lipase gene

for (gene in lipases) {
  #pdf(sprintf('../figures/Acromegaly-%s-barplot.pdf', gene))
  gene.data <- lipase.cal[lipase.cal$Genes==gene,]
  #pdf(paste('../figures/Acromegaly-',gene,'-barplot.pdf',sep=""))
  ggplot(gene.data, aes(x=Disease,y=mean_Expression, fill=Age)) + 
    geom_bar(stat="identity", position="dodge", col="black") + 
    geom_errorbar(aes(ymin=mean_Expression-se, ymax=mean_Expression+se), position=position_dodge(0.9),width=.2) + 
    scale_x_discrete(labels=gene.data$Disease) + 
    xlab("") + ylab("RPKM")+ theme_bw() + ggtitle(gene) + 
    theme(panel.grid.minor = element_blank()) + 
    theme(panel.grid.major = element_blank()) + 
    theme(panel.border=element_blank()) + 
    theme(axis.line = element_line(color = 'black'))
  
  ggsave(filename=paste('../Figures/Acro_Age/Acro-Age-lipase-',gene,'-barplot.pdf',sep=""))
}
```

```{r drawing gene insulin and lipolysis signaling pathway, echo=FALSE, fig.show='asis' }
insulin <- c("FASN", "TCF7L2", "SOCS2", "AKT1", "PYGM", "ACACA", "SLC2A4")
unsat_FA <- c("ELOVL5", "ELOVL6", "FADS1", "FADS2", "SCD", "HSD17B12", "ACOX1", "HADHA", "PECR")
lipolysis <- c("LPL", "ABHD5", "ADRB3", "ACVR1C", "PNPLA", "LIPE", "MGLL", "PNPLA2")

figureXX <- c("SOCS2", "CISH")
figureX <- c("MAPK3","MAPK7","FOS","JUN","JUNB")
figure1A <- c("PTPN3", "PTPN4")
figure1B <- c("CCNC","CCNE1","CDKN2B")
figure1C <- c("NAP1L1","ORC2","BAG4","CAPN6")
figure1D <- c("MAP3K5","MAPK14","MAPK13","MAPKAPK3")
figure4A <- c("LPL","PNPLA2","LIPE","MGLL")
figure4B <- c("ABHD5","NRIP1","ADRB1", "ADRB2", "ADRB3", "CALCRL")
figure4C <- c("AACS","ACACA","ACSL3")
figure4C_FASN <- c("FASN")
figure4D <- c("FADS1","FADS2","CYB5A")
figure4D_SCD <- c("SCD")
sup1E <- c("UGP2", "PYGM")
sup2A <- c("INSR","IRS1","IRS2","AKT1","AKT2","AKT3","SLC2A4")
sup2B <- c("STAT6","IKBKB","IL1B","IL6","MCP1","IKBKE")
sup2C <- c("HSD11B1","HSD11B2","NR3C1","NR3C2")
figureIGF_IGFBP3 <- c("IGF1","IGFBP3")
igf_complex <- c("IGF1","IGFBP3", "IGFBP5", "IGFALS")
ags_isoforms <- c("GPSM1","GPSM2","GPSM3")
rgs_isoforms <- paste("RGS", seq(1,22), sep="")
ptps <- paste("PTPN", seq(1,23), sep="")
socs_isoforms <- paste("SOCS", seq(1,7), sep="")

gene.data.name <- c('figureXX', 'figureX', 'figure1A', 'figure1B', 'figure1C', 'figure1D', 
                    'figure4A', 'figure4B', 'figure4C', 'figure4D', 'sup1E', 'sup2A', 'sup2B', 'sup2C','igf_complex','rgs_isoforms','ags_isoforms','ptps','socs_isoforms')

for (name in gene.data.name){
  #name <- as.name(name) #convert string to variable name
  gene.data <- rpkm.long.cal[rpkm.long.cal$hgnc_symbol%in%eval(as.name(name)),]
  gene.data$hgnc_symbol <- factor(gene.data$hgnc_symbol, levels=eval(as.name(name)))
  
  ggplot(gene.data, aes(x=hgnc_symbol, y=mean_Expression, fill=Disease))+ 
    #this line together with show_guide=F and the element_rect=black get rid of the slash in legend box
    geom_bar(stat="identity", width=.8, position=position_dodge(width=.8)) +
    geom_bar(stat="identity",width=.8, position=position_dodge(width=.8), col="black", show_guide=F) +
    geom_errorbar(position=position_dodge(width=.8), aes(ymin=mean_Expression-se, ymax=mean_Expression+se), width=.2)+
    facet_grid(Age~.)+
    theme_bw()+theme(axis.text.x=element_text(angle=90))+xlab("")+ ylab("mRNA Expression (RPKM)") +
    theme(panel.grid.minor = element_blank()) + 
    #theme(panel.grid.major = element_blank()) + 
    #theme(panel.border=element_blank())+ 
    theme(axis.line = element_line(color = 'black')) +
    scale_fill_grey(start = 0.3, end = .9, guide=guide_legend()) +
    #guides(fill = guide_legend(keywidth = .5, keyheight = .5)) +
    theme(text = element_text(size=20), axis.text.x = element_text(angle=70,hjust=.5,vjust=.5)) +
    theme(legend.position=c(.25,.90), legend.title=element_blank(), legend.key=element_rect(color="black"))   + ggtitle(name)
    
  ggsave(filename=paste('../Figures/Acro_Age/Acro-Age', name, '-barplot.pdf',sep=""))
}

gene.data.name <- c('figure4C', 'figure4C_FASN','figure4D_SCD', 'figure4D')

for (name in gene.data.name){
  #name <- as.name(name) #convert string to variable name
  gene.data <- rpkm.long.cal[rpkm.long.cal$hgnc_symbol%in%eval(as.name(name)),]
  gene.data$hgnc_symbol <- factor(gene.data$hgnc_symbol, levels=eval(as.name(name)))
  
  assign(sprintf("plot_%s", name), ggplot(gene.data, aes(x=hgnc_symbol, y=mean_Expression, fill=Disease))+ 
    #this line together with show_guide=F and the element_rect=black get rid of the slash in legend box
    geom_bar(stat="identity", width=.8, position=position_dodge(width=.8)) +
    geom_bar(stat="identity",width=.8, position=position_dodge(width=.8), col="black", show_guide=F) +
    geom_errorbar(position=position_dodge(width=.8), aes(ymin=mean_Expression-se, ymax=mean_Expression+se), width=.2)+
    facet_grid(Age~.)+
    theme_bw()+theme(axis.text.x=element_text(angle=90))+xlab("")+ ylab("mRNA Expression (RPKM)") +
    theme(panel.grid.minor = element_blank()) + 
    #theme(panel.grid.major = element_blank()) + 
    #theme(panel.border=element_blank())+ 
    theme(axis.line = element_line(color = 'black')) +
    scale_fill_grey(start = 0.3, end = .9, guide=guide_legend()) +
    #guides(fill = guide_legend(keywidth = .5, keyheight = .5)) +
    theme(text = element_text(size=20), axis.text.x = element_text(angle=70,hjust=.5,vjust=.5)) +
    theme(legend.position=c(.25,.90), legend.title=element_blank(), legend.key=element_rect(color="black")))
}

#build multiplot function

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  require(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
  
pdf('../Figures/Acro_Age/Acromegaly_Age_FASN_Combined.pdf')
multiplot(plot_figure4C,plot_figure4C_FASN, cols=2)
dev.off()

pdf('../Figures/Acro_Age/Acromegaly_Age_SCD_Combined.pdf')
multiplot(plot_figure4D_SCD,plot_figure4D, cols=2)
dev.off()
```


The data used is in the file **`r filename`**.  This file was most recently processed on ```r date()```.


Session Information
---------------------

```{r session-information}
sessionInfo()
```
