Analysis of Clinical Data for Cushing Patients
=============================================================

This file was last compiled on ```r date()```.  Unless otherwise noted this analysis removes subject 29.

Statistics
-------------

```{r data entry, echo=FALSE, message=FALSE}
data <- read.csv('../data/raw/patient_table.csv')
#removed cushing data
cushing.data <- subset(data, diagnosis %in% c("cushing's", "non secreting adenoma"), drop=TRUE)
#reset non secreting adenoma to 
levels(cushing.data$diagnosis)[3] <- "Control"
levels(cushing.data$diagnosis)[2] <- "Cushing's"
cushing.data$diagnosis <- relevel(cushing.data$diagnosis, ref = "Control")
#set qualitative variables to logicals
cushing.data$diabetes.diagnosis <- cushing.data$diabetes == "y"
cushing.data$HTN.diagnosis <- cushing.data$HTN == "y"
cushing.data$smoking.diagnosis <- cushing.data$smoking == "y"
require(reshape2, quietly=T)
require(plyr, quietly=T)

melted.data.all <- melt(cushing.data, id.vars=c("id", "initials", "diagnosis"), na.rm=T, variable.name="measurement")
melted.data <- subset(melted.data.all, !(measurement %in% c("HTN","diabetes","smoking","HTN.diagnosis","diabetes.diagnosis","smoking.diagnosis")))
melted.data$value <- as.numeric(melted.data$value)
#removed outlier subject 29
melted.data.used <- subset(melted.data, id!='29')
melted.data.used <- droplevels(melted.data.used)
se <- function (x) sd(x, na.rm=T)/sqrt(length(x))

#for bibliography
library(bibtex)
library(knitcitations)
bib <- read.bib(file = "clinical-tests.bib")
```

This analysis included `r as.numeric(summary(cushing.data$diagnosis)[1])-1` controls and `r as.numeric(summary(cushing.data$diagnosis)[3])` cushing patients. 

```{r, preliminary-analysis, echo=FALSE}
test.summary.table <- data.frame(row.names=levels(melted.data.used$measurement),
                                 shapiro.control = rep(NA, length(levels(melted.data.used$measurement))),
                                 shapiro.cushing = rep(NA, length(levels(melted.data.used$measurement))),
                                 levene.test = rep(NA, length(levels(melted.data.used$measurement))))

library(car) #for leveneTest

#forloop for all these tests
for (param in levels(melted.data.used$measurement)) {
  test.summary.table[param,'shapiro.control'] <- 
    with(subset(melted.data.used, measurement==param&diagnosis=='Control'), shapiro.test(value))$p.value
  test.summary.table[param,'shapiro.cushing'] <- 
    with(subset(melted.data.used, measurement==param&diagnosis=="Cushing's"), shapiro.test(value))$p.value
  test.summary.table[param,'levene.test'] <- 
    leveneTest(value~diagnosis, data=subset(melted.data.used, measurement==param))$`Pr(>F)`[1]
}
test.summary.table$test <- ifelse(test.summary.table$shapiro.control<0.05|test.summary.table$shapiro.cushing<0.05, 
                                  "Wilcoxon Test", 
                                  ifelse(test.summary.table$levene.test<0.05, "Welch's T-Test", "Student's T-Test"))
test_output_file <- "../data/processed/Clinical Test Parameters - Cushings.csv"
write.csv(test.summary.table, test_output_file)
```

First we checked whether the data was normally distributed using a Shapiro-Wilk test.  If a Shapiro-Wilk Normality test had a p-value <0.05 for a measurement in either the control or the cushing cases, we did a Wilcoxon test. This was appropriate for `r rownames(test.summary.table[test.summary.table$test == 'Wilcoxon Test',])`.

We next tested, for the normally distributed data, whether the data had unequal variance.  This was done using Levene's test in the car package `r citet(bib[["car"]])`.  A Welch's t-test for unequal variance was appropriate for `r rownames(test.summary.table[test.summary.table$test == "Welch's T-Test",])` based on p<0.05.  In all other cases, a t-test, presuming equal variance was used.


```{r analysis, echo=FALSE}
#for glucose homeostatic measurements
glucose.data.vars <- c("insulin", "glucose", "HOMA.IR")
#for clinical measurements
clinical.data.vars <- c("height", "weight", "age", "BMI", "abdominal.circumference")

#for lipidomics data
lipid.data.vars <- c("Cer.C14", "Cer.C16", "Cer.C18", "Cer.C18.1", "Cer.C20", "Cer.C24", "Glu.Cer.C16", "Glu.Cer.C18", "Glu.Cer.C18.1")

#for lipolysis measurements
lipolysis.data.vars <- c("glycerol.no.tx","glycerol.insulin.2.nM","glycerol.iso.30.nM","glycerol.ins.iso","glycerol.ins.ctrl","glycerol.iso.ctrl","glycerol.ins.iso.iso","glycerol.ins.effect", "glycerol.iso.effect")

#for all measurements
all.o1 <- ddply(melted.data.used, .(diagnosis, measurement), summarise, mean = mean(value), se=se(value))

#these are the measurements that should have a Wilcoxon test
all.o2.wilcoxon <- ddply(melted.data.used[melted.data.used$measurement %in% rownames(test.summary.table[test.summary.table$test == 'Wilcoxon Test',]),]
                , .(measurement), summarise, pval=wilcox.test(value ~ diagnosis)$p.value)

#these are the measurements that should have a Welch's t-test
all.o2.welch <- ddply(melted.data.used[melted.data.used$measurement %in% rownames(test.summary.table[test.summary.table$test == "Welch's T-Test",]),]
                , .(measurement), summarise, pval=t.test(value ~ diagnosis, var.equal=F)$p.value)

#these are the measurements that should have a Student's t-test
all.o2.student <- ddply(melted.data.used[melted.data.used$measurement %in% rownames(test.summary.table[test.summary.table$test == "Student's T-Test",]),]
                , .(measurement), summarise, pval=t.test(value ~ diagnosis, var.equal=T)$p.value)

all.o2 <- rbind(all.o2.wilcoxon,all.o2.welch, all.o2.student)

all.o1.mc <- dcast(melt(all.o1, c("diagnosis", "measurement")), measurement ~ diagnosis + variable)
all.summary.table <- merge(all.o1.mc, all.o2)
all.summary.table$padj <- p.adjust(all.summary.table$pval, method="BH")

glucose.summary.table <- all.summary.table[all.summary.table$measurement %in% glucose.data.vars,]
lipolysis.summary.table <- all.summary.table[all.summary.table$measurement %in% lipolysis.data.vars,]
```

```{r table, results='asis', echo=FALSE} 
library(xtable) 
print(xtable(all.summary.table[order(all.summary.table$pval),], digits=c(rep(1,6),5,5)), type='html') 
``` 

Graphs
------

## Barplots
```{r barplots, echo=FALSE, warning=FALSE, message=FALSE}
superpose.eb <- function (x, y, ebl, ebu = ebl, length = 0.08, ...)
arrows(x, y + ebu, x, y - ebl, angle = 90, code = 3,
length = length, ...)

pdf("../figures/Cushing - HOMA Barplot.pdf")
#HOMA Score
plot <- with(glucose.summary.table, 
     barplot(cbind(Control_mean[2], `Cushing's_mean`[2]),
             names.arg=c("Control", "Cushing's"),
             main="HOMA Score",las=1,
             ylim=c(0,(`Cushing's_mean`+`Cushing's_se`)[2])))
with(glucose.summary.table, superpose.eb(plot, cbind(Control_mean[2], `Cushing's_mean`[2]), cbind(Control_se[2], `Cushing's_se`[2])))
dev.off()

plot <- with(glucose.summary.table, 
     barplot(cbind(Control_mean[2], `Cushing's_mean`[2]),
             names.arg=c("Control", "Cushing's"),
             main="HOMA Score",las=1,
             ylim=c(0,(`Cushing's_mean`+`Cushing's_se`)[2])))
with(glucose.summary.table, superpose.eb(plot, cbind(Control_mean[2], `Cushing's_mean`[2]), cbind(Control_se[2], `Cushing's_se`[2])))

#Glucose
pdf("../figures/Cushing - Glucose Barplot.pdf")
plot <- with(glucose.summary.table, 
     barplot(cbind(Control_mean[1], `Cushing's_mean`[1]),
             names.arg=c("Control", "Cushing's"),
             main="Fasting Blood Glucose",
             ylab="Glucose (mg/dL)",las=1,
             ylim=c(0,(`Cushing's_mean`+`Cushing's_se`)[1])))
with(glucose.summary.table, superpose.eb(plot, cbind(Control_mean[1], `Cushing's_mean`[1]), cbind(Control_se[1], `Cushing's_se`[1])))
dev.off()

plot <- with(glucose.summary.table, 
     barplot(cbind(Control_mean[1], `Cushing's_mean`[1]),
             names.arg=c("Control", "Cushing's"),
             main="Fasting Blood Glucose",
             ylab="Glucose (mg/dL)",las=1,
             ylim=c(0,(`Cushing's_mean`+`Cushing's_se`)[1])))
with(glucose.summary.table, superpose.eb(plot, cbind(Control_mean[1], `Cushing's_mean`[1]), cbind(Control_se[1], `Cushing's_se`[1])))

#Insulin
plot <- with(glucose.summary.table, 
     barplot(cbind(Control_mean[3], `Cushing's_mean`[3]),
             names.arg=c("Control", "Cushing's"),
             main="Fasting Insulin",
             ylab="Serum Insulin (pg/mL)",
             las=1,
             ylim=c(0,(`Cushing's_mean`+`Cushing's_se`)[3])))
with(glucose.summary.table, superpose.eb(plot, cbind(Control_mean[3], `Cushing's_mean`[3]), cbind(Control_se[3], `Cushing's_se`[3])))

pdf("../figures/Cushing - Insulin Barplot.pdf")
plot <- with(glucose.summary.table, 
     barplot(cbind(Control_mean[3], `Cushing's_mean`[3]),
             names.arg=c("Control", "Cushing's"),
             main="Fasting Insulin",
             ylab="Serum Insulin (pg/mL)",
             las=1,
             ylim=c(0,(`Cushing's_mean`+`Cushing's_se`)[3])))
with(glucose.summary.table, superpose.eb(plot, cbind(Control_mean[3], `Cushing's_mean`[3]), cbind(Control_se[3], `Cushing's_se`[3])))
dev.off()

#Lipolysis-Basal
pdf("../figures/Cushing - Basal Lipolysis Barplot.pdf")
plot <- with(lipolysis.summary.table, 
     barplot(cbind(Control_mean[7], `Cushing's_mean`[7]),
             names.arg=c("Control", "Cushing's"),
             main="Basal Lipolysis",
             ylab="Glycerol Release",
             las=1,
             ylim=c(0,(`Cushing's_mean`+`Cushing's_se`)[7])))
with(lipolysis.summary.table, superpose.eb(plot, cbind(Control_mean[7], `Cushing's_mean`[7]), cbind(Control_se[7], `Cushing's_se`[7])))
dev.off()

plot <- with(lipolysis.summary.table, 
     barplot(cbind(Control_mean[7], `Cushing's_mean`[7]),
             names.arg=c("Control", "Cushing's"),
             main="Basal Lipolysis",
             ylab="Glycerol Release",
             las=1,
             ylim=c(0,(`Cushing's_mean`+`Cushing's_se`)[7])))
with(lipolysis.summary.table, superpose.eb(plot, cbind(Control_mean[7], `Cushing's_mean`[7]), cbind(Control_se[7], `Cushing's_se`[7])))

#Lipolysis-Isoproterenol
pdf("../figures/Cushing - Isoproterenol Stimulated Lipolysis Barplot.pdf")
plot <- with(lipolysis.summary.table, 
     barplot(cbind(Control_mean[5], `Cushing's_mean`[5]),
             names.arg=c("Control", "Cushing's"),
             main="Isoproternol Stimulated Lipolysis",
             ylab="Glycerol Release",
             las=1,
             ylim=c(0,(`Cushing's_mean`+`Cushing's_se`)[5])))
with(lipolysis.summary.table, superpose.eb(plot, cbind(Control_mean[5], `Cushing's_mean`[5]), cbind(Control_se[5], `Cushing's_se`[5])))
dev.off()

plot <- with(lipolysis.summary.table, 
     barplot(cbind(Control_mean[5], `Cushing's_mean`[5]),
             names.arg=c("Control", "Cushing's"),
             main="Isoproternol Stimulated Lipolysis",
             ylab="Glycerol Release",
             las=1,
             ylim=c(0,(`Cushing's_mean`+`Cushing's_se`)[5])))
with(lipolysis.summary.table, superpose.eb(plot, cbind(Control_mean[5], `Cushing's_mean`[5]), cbind(Control_se[5], `Cushing's_se`[5])))

pdf("../figures/Cushing - Combined Lipolysis Barplot.pdf")
plot <- with(lipolysis.summary.table, 
     barplot(cbind(rbind(Control_mean[7], `Cushing's_mean`[7]),rbind(Control_mean[5], `Cushing's_mean`[5])),
             names.arg=c("Basal","Isoproterenol"), 
             main="Lipolysis",
             beside=T,
             ylab="Glycerol Release",
             las=1,
             ylim=c(0,(`Cushing's_mean`+`Cushing's_se`)[7])))
with(lipolysis.summary.table, superpose.eb(plot, 
    cbind(rbind(Control_mean[7], `Cushing's_mean`[7]),rbind(Control_mean[5], `Cushing's_mean`[5])),
    cbind(rbind(Control_se[7], `Cushing's_se`[7]),rbind(Control_se[5], `Cushing's_se`[5]))))
legend("topleft", c("Control", "Cushing's"), fill=grey.colors(2), bty="n")
dev.off()

plot <- with(lipolysis.summary.table, 
     barplot(cbind(rbind(Control_mean[7], `Cushing's_mean`[7]),rbind(Control_mean[5], `Cushing's_mean`[5])),
             names.arg=c("Basal","Isoproterenol"), 
             main="Lipolysis",
             beside=T,
             ylab="Glycerol Release",
             las=1,
             ylim=c(0,(`Cushing's_mean`+`Cushing's_se`)[7])))
with(lipolysis.summary.table, superpose.eb(plot, 
    cbind(rbind(Control_mean[7], `Cushing's_mean`[7]),rbind(Control_mean[5], `Cushing's_mean`[5])),
    cbind(rbind(Control_se[7], `Cushing's_se`[7]),rbind(Control_se[5], `Cushing's_se`[5]))))
legend("topleft", c("Control", "Cushing's"), fill=grey.colors(2), bty="n")

#clinical variables
pdf('../figures/Cushing - Clinical Barplots.pdf')
par(mfrow=c(1,3))
#Age
plot <- with(all.summary.table[all.summary.table$measurement=='age',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="Age",
             ylab="Years",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,70)))
with(all.summary.table[all.summary.table$measurement=='age',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))

#height
plot <- with(all.summary.table[all.summary.table$measurement=='height',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="Height",
             ylab="Height (cm)",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,185)))
with(all.summary.table[all.summary.table$measurement=='height',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))

#tumor diameter
plot <- with(all.summary.table[all.summary.table$measurement=='largest.diameter.of.tumor',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="Largest Tumor Diameter",
             ylab="Diameter (mm)",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,2.2)))
with(all.summary.table[all.summary.table$measurement=='largest.diameter.of.tumor',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))
dev.off()

par(mfrow=c(1,3))
#Age
plot <- with(all.summary.table[all.summary.table$measurement=='age',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="Age",
             ylab="Years",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,70)))
with(all.summary.table[all.summary.table$measurement=='age',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))

#height
plot <- with(all.summary.table[all.summary.table$measurement=='height',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="Height",
             ylab="Height (cm)",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,185)))
with(all.summary.table[all.summary.table$measurement=='height',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))

#tumor diameter
plot <- with(all.summary.table[all.summary.table$measurement=='largest.diameter.of.tumor',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="Largest Tumor Diameter",
             ylab="Diameter (mm)",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,2.2)))
with(all.summary.table[all.summary.table$measurement=='largest.diameter.of.tumor',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))

#weight (kg), BMI (kg/m2), abdominal circumference (cm),
#weight variables
pdf('../figures/Cushing - Weight Barplots.pdf')
par(mfrow=c(1,3))
#weight
plot <- with(all.summary.table[all.summary.table$measurement=='weight',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="Weight",
             ylab="Weight (kg)",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,115)))
with(all.summary.table[all.summary.table$measurement=='weight',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))


#BMI
plot <- with(all.summary.table[all.summary.table$measurement=='BMI',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="Body Mass Index",
             ylab="BMI (kg/cm2)",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,35)))
with(all.summary.table[all.summary.table$measurement=='BMI',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))


#abdominal circuference

plot <- with(all.summary.table[all.summary.table$measurement=='abdominal.circumference',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="Admdominal Circumference",
             ylab="Circumference (cm)",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,130)))
with(all.summary.table[all.summary.table$measurement=='abdominal.circumference',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))
dev.off()

par(mfrow=c(1,3))
#weight
plot <- with(all.summary.table[all.summary.table$measurement=='weight',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="Weight",
             ylab="Weight (kg)",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,115)))
with(all.summary.table[all.summary.table$measurement=='weight',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))


#BMI
plot <- with(all.summary.table[all.summary.table$measurement=='BMI',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="Body Mass Index",
             ylab="BMI (kg/cm2)",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,40)))
with(all.summary.table[all.summary.table$measurement=='BMI',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))


#abdominal circuference

plot <- with(all.summary.table[all.summary.table$measurement=='abdominal.circumference',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="Admdominal Circumference",
             ylab="Circumference (cm)",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,130)))
with(all.summary.table[all.summary.table$measurement=='abdominal.circumference',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))

#ALT and AST
pdf('../figures/Cushing - Liver Enzyme Barplots.pdf')
par(mfrow=c(1,2))
plot <- with(all.summary.table[all.summary.table$measurement=='ALT',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="ALT",
             ylab="IU/L",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,80)))
with(all.summary.table[all.summary.table$measurement=='ALT',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))

plot <- with(all.summary.table[all.summary.table$measurement=='AST',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="AST",
             ylab="IU/L",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,40)))
with(all.summary.table[all.summary.table$measurement=='AST',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))
dev.off()

par(mfrow=c(1,2))
plot <- with(all.summary.table[all.summary.table$measurement=='ALT',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="ALT",
             ylab="IU/L",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,80)))
with(all.summary.table[all.summary.table$measurement=='ALT',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))

plot <- with(all.summary.table[all.summary.table$measurement=='AST',], 
     barplot(cbind(Control_mean, `Cushing's_mean`),
             names.arg=c("Control", "Cushing's"),
             main="AST",
             ylab="IU/L",
             las=1,             col=grey.colors(2)[2],
             ylim=c(0,40)))
with(all.summary.table[all.summary.table$measurement=='AST',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`), cbind(Control_se, `Cushing's_se`)))
```

Correlation with BMI
-----------------------

```{r bmi-correction, echo=FALSE}
bmi.lm <- lm(log(HOMA.IR)~BMI, data=cushing.data[cushing.data$id!='29',])
bmi.diagnosis.lm <- lm(log(HOMA.IR)~BMI+diagnosis, data=cushing.data[cushing.data$id!='29',])
bmi.diagnosis.interaction.lm <- lm(log(HOMA.IR)~BMI*diagnosis, data=cushing.data[cushing.data$id!='29',])
```

The HOMA score significantly correlated with the natural logarithm of the BMI (p=`r with(cushing.data[cushing.data$id!='29',], cor.test(log(HOMA.IR), BMI))$p.value`, r=`r with(cushing.data[cushing.data$id!='29',], cor.test(log(HOMA.IR), BMI))$estimate`, R2=`r with(cushing.data[cushing.data$id!='29',], cor.test(log(HOMA.IR), BMI))$estimate^2`)To correct for the BMI effect on the HOMA-IR score, I generated a linear model comparing the HOMA score to the BMI and the diagnosis.  We tested for an interaction between HOMA-IR and BMI in this model, and did not observe any evidence of an interaction (p=`r anova(bmi.diagnosis.lm, bmi.diagnosis.interaction.lm)[2,6]`).

```{r anova-table, results='asis', echo=FALSE} 
print(xtable(bmi.diagnosis.lm), type='html') 
print(xtable(exp(confint(bmi.diagnosis.lm))), type='html')
``` 

The results of this linear model are a significant main effect of BMI (p=`r summary(bmi.diagnosis.lm)$coefficients[2,4]`) but not the the diagnosis (p=`r summary(bmi.diagnosis.lm)$coefficients[3,4]`) with a r-squared value of `r summary(bmi.diagnosis.lm)$adj.r.squared`.  This corresponds to an effect size of `r exp(as.numeric(coef(bmi.diagnosis.lm)[3]))`.

### Model Plot

```{r correlation-plot}
pdf('../figures/Cushing - BMI-HOMA Correlation.pdf')
with(cushing.data, plot(BMI, log(HOMA.IR),
                           pch=19,las=1,
    col=diagnosis, ylab='Log HOMA-IR Score', xlab="BMI (mg/kg2)"))
legend("topleft", levels(cushing.data$diagnosis)[c(1,3)], pch=19, bty="n", col=palette()[c(1,3)], lty=1)
with(cushing.data[cushing.data$diagnosis == "Control"&cushing.data$id!='29',], abline(lm(log(HOMA.IR)~BMI), col=palette()[1]))
with(cushing.data[cushing.data$diagnosis == "Cushing's"&cushing.data$id!='29',], abline(lm(log(HOMA.IR)~BMI), col=palette()[3]))
dev.off()

with(cushing.data, plot(BMI, log(HOMA.IR),
                           pch=19,las=1,
    col=diagnosis, ylab='Log HOMA-IR Score', xlab="BMI (mg/kg2)"))
legend("topleft", levels(cushing.data$diagnosis)[c(1,3)], pch=19, bty="n", col=palette()[c(1,3)], lty=1)
with(cushing.data[cushing.data$diagnosis == "Control"&cushing.data$id!='29',], abline(lm(log(HOMA.IR)~BMI), col=palette()[1]))
with(cushing.data[cushing.data$diagnosis == "Cushing's"&cushing.data$id!='29',], abline(lm(log(HOMA.IR)~BMI), col=palette()[3]))
```
### Model Diagnostics
```{r, model-diagnostic-plots, echo=FALSE}
par(mfrow=c(2,2))
plot(bmi.diagnosis.lm)
```

Separation out of Outlier Data
--------------------------------

One subject was identified as an outlier based on the heatmap.  This was sample 12100, subject #29.

```{r outlier-data, echo=FALSE}
#for all measurements
outlier_subject <- '29'
outlier.all.o1 <- ddply(melted.data[melted.data$id!=outlier_subject,], .(diagnosis, measurement), summarise, mean = mean(value), se=se(value))
outlier.all.o2 <- ddply(melted.data[melted.data$id!=outlier_subject,], .(measurement), summarise, pval=t.test(value ~ diagnosis)$p.value)
outlier.all.o1.mc <- dcast(melt(outlier.all.o1, c("diagnosis", "measurement")), measurement ~ diagnosis + variable)
outlier.all.summary.table <- merge(outlier.all.o1.mc, all.o2, all.x=T)
outlier.all.summary.table$padj <- p.adjust(outlier.all.summary.table$pval, method="BH")
outlier.all.summary.table <- merge(
  outlier.all.summary.table,
  melted.data[melted.data$id==outlier_subject,c('measurement','value')],
  all.x=T
)
```

```{r outlier-barplots, echo=FALSE, warning=FALSE, messages=FALSE}

pdf("../figures/Cushing - HOMA Barplot - Outlier.pdf")
#HOMA Score
plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='HOMA.IR',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's", "Outlier"),
             main="HOMA Score",las=1,
             ylim=c(0,8)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='HOMA.IR',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))
dev.off()

plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='HOMA.IR',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's", "Outlier"),
             main="HOMA Score",las=1,
             ylim=c(0,8)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='HOMA.IR',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))

#Glucose
pdf("../figures/Cushing - Glucose Barplot - Outlier.pdf")
plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='glucose',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's", "Outlier"),
             main="Fasting Blood Glucose",las=1,
             ylab="Glucose (mg/dL)",
             ylim=c(0,140)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='glucose',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))
dev.off()

plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='glucose',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's", "Outlier"),
             main="Fasting Blood Glucose",las=1,
             ylab="Glucose (mg/dL)",
             ylim=c(0,160)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='glucose',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))

#Insulin
pdf("../figures/Cushing - Insulin Barplot - Outlier.pdf")
plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='insulin',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's", "Outlier"),
             main="Fasting Insulin",
             ylab="Serum Insulin (pg/mL)",
             las=1,
             ylim=c(0,28)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='insulin',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))
dev.off()

plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='insulin',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's", "Outlier"),
             main="Fasting Insulin",
             ylab="Serum Insulin (pg/mL)",
             las=1,
             ylim=c(0,28)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='insulin',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))

#Lipolysis-Basal
pdf("../figures/Cushing - Basal Lipolysis Barplot - Outlier.pdf")
plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='glycerol.no.tx',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's", "Outlier"),
             main="Basal Lipolysis",
             ylab="Glycerol Release",
             las=1,
             ylim=c(0,22)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='glycerol.no.tx',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))
dev.off()

plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='glycerol.no.tx',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's", "Outlier"),
             main="Basal Lipolysis",
             ylab="Glycerol Release",
             las=1,
             ylim=c(0,22)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='glycerol.no.tx',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))

#Lipolysis-Isoproterenol
pdf("../figures/Cushing - Isoproterenol Stimulated Lipolysis Barplot - Outlier.pdf")
plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='glycerol.iso.30.nM',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's", "Outlier"),
             main="Isoproternol Stimulated Lipolysis",
             ylab="Glycerol Release",
             las=1,
             ylim=c(0,10)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='glycerol.iso.30.nM',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))
dev.off()

plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='glycerol.iso.30.nM',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's", "Outlier"),
             main="Isoproternol Stimulated Lipolysis",
             ylab="Glycerol Release",
             las=1,
             ylim=c(0,10)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='glycerol.iso.30.nM',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))

#clinical variables
pdf('../figures/Cushing - Clinical Barplots - Outlier.pdf')
par(mfrow=c(1,2))
#Age
plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='age',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's","Outlier"),
             main="Age",
             ylab="Years",
             las=2,
             ylim=c(0,70)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='age',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))

#height
plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='height',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's","Outlier"),
             main="Height",
             ylab="Height (cm)",
             las=2,
             ylim=c(0,190)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='height',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))


par(mfrow=c(1,2))
#Age
plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='age',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's","Outlier"),
             main="Age",
             ylab="Years",
             las=2,
             ylim=c(0,70)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='age',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))

#height
plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='height',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's","Outlier"),
             main="Height",
             ylab="Height (cm)",
             las=2,
             ylim=c(0,190)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='height',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))


#weight (kg), BMI (kg/m2), abdominal circumference (cm),
#weight variables
pdf('../figures/Cushing - Weight Barplots - Outlier.pdf')
par(mfrow=c(1,3))
#weight
plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='weight',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's","Outlier"),
             main="Weight",
             ylab="Weight (kg)",
             las=2,
             ylim=c(0,120)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='weight',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))

#BMI
plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='BMI',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's","Outlier"),
             main="Body Mass Index",
             ylab="BMI (kg/cm2)",
             las=2,
             ylim=c(0,45)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='BMI',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`, value), cbind(Control_se, `Cushing's_se`,0)))

#abdominal circuference
plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='abdominal.circumference',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's","Outlier"),
             main="Admdominal Circumference",
             ylab="Circumference (cm)",
             las=2,
             ylim=c(0,130)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='abdominal.circumference',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))
dev.off()

plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='weight',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's","Outlier"),
             main="Weight",
             ylab="Weight (kg)",
             las=2,
             ylim=c(0,120)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='weight',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))

#BMI
plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='BMI',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's","Outlier"),
             main="Body Mass Index",
             ylab="BMI (kg/cm2)",
             las=2,
             ylim=c(0,45)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='BMI',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`, value), cbind(Control_se, `Cushing's_se`,0)))

#abdominal circuference
plot <- with(outlier.all.summary.table[outlier.all.summary.table$measurement=='abdominal.circumference',], 
     barplot(cbind(Control_mean, `Cushing's_mean`,value),
             names.arg=c("Control", "Cushing's","Outlier"),
             main="Admdominal Circumference",
             ylab="Circumference (cm)",
             las=2,
             ylim=c(0,130)))
with(outlier.all.summary.table[outlier.all.summary.table$measurement=='abdominal.circumference',], superpose.eb(plot, cbind(Control_mean, `Cushing's_mean`,value), cbind(Control_se, `Cushing's_se`,0)))
```

Ceramides
----------

We tested whether ceramides were elevated in cushing patients.

```{r ceramides-barplots, echo=FALSE, warning=FALSE, messages=FALSE}
lipid.data <- droplevels(subset(melted.data, measurement %in% lipid.data.vars))
lipid.data$measurement <- factor(lipid.data$measurement, levels=lipid.data.vars)
lipid.summary <- ddply(lipid.data, .(diagnosis,measurement), summarise,
                       mean = mean(value),
                       sd = sd(value),
                       se = sd(value)/sqrt(length(value)),
                       n = length(value))
lipid.summary$rel.mean <- lipid.summary$mean/lipid.summary$mean[1:9]
lipid.summary$rel.se <- lipid.summary$se/lipid.summary$mean[1:9]

pdf('../figures/Cushing - Ceramide Levels.pdf')
par(mar=c(8,4.1,4.1,2.1))
plot <- barplot(as.matrix(dcast(lipid.summary, diagnosis~measurement, value.var='rel.mean')[2:10]), beside=T, las=2, ylab="Relative Levels", ylim=c(0,2.5))
superpose.eb(plot, 
             as.matrix(dcast(lipid.summary, diagnosis~measurement, value.var='rel.mean')[2:10]),
             as.matrix(dcast(lipid.summary, diagnosis~measurement, value.var='rel.se')[2:10]))
dev.off()

par(mar=c(8,4.1,4.1,2.1))
plot <- barplot(as.matrix(dcast(lipid.summary, diagnosis~measurement, value.var='rel.mean')[2:10]), beside=T, las=2, ylab="Relative Levels", ylim=c(0,2.5))
superpose.eb(plot, 
             as.matrix(dcast(lipid.summary, diagnosis~measurement, value.var='rel.mean')[2:10]),
             as.matrix(dcast(lipid.summary, diagnosis~measurement, value.var='rel.se')[2:10]))

lipid.summary.table <- all.summary.table[all.summary.table$measurement %in% lipid.data.vars,]
lipid.summary.table$padj <- p.adjust(lipid.summary.table$pval, method="BH")
```

```{r lipid-table, results='asis', echo=FALSE} 
library(xtable) 
print(xtable(lipid.summary.table[order(lipid.summary.table$pval),], digits=c(rep(1,6),5,5)), type='html') 
``` 

References
-----------
```{r, results='asis', echo=FALSE, message=FALSE}
write.bibtex(c(car=citation("car"), base=citation("stats")), file = "clinical-tests.bib")
bibliography("html")
```



Session Information
-------------------
```{r session-info}
sessionInfo()
```
