---
title: "Analysis of Gastroc mRNA Transcripts"
author: "Innocence Harvey and Dave Bridges"
date: "February 25, 2015"
output:
  html_document:
    keep_md: yes
  pdf_document:
    keep_tex: yes
---

```{r global_options, include=FALSE}
library(knitr)
opts_chunk$set(fig.path='figures/',
               echo=FALSE, warning=FALSE, message=FALSE,dev=c('png','pdf'))
```

# Data Entry


```{r data-entry}
data_file <- '../data/raw/Fat Pad Weights.csv'
data <- read.csv(data_file)
#set the treatment
data$Treatment <- relevel(data$Treatment, ref='Water')
```

Data was read from the file `r data_file`.  These data were most recently updated on `r date()`.

#Analysis

```{r analysis}
library(dplyr)
fat.summary <- 
  data %>%
  group_by(Treatment) %>%
  summarise(mean.iwat = mean(Iwat),
            se.iwat = sd(Iwat)/sqrt(length(Iwat)),
            mean.ewat = mean(Ewat),
            se.ewat = sd(Ewat)/sqrt(length(Ewat)),
            mean.weight = mean(Body.Weight),
            se.weight = sd(Body.Weight)/sqrt(length(Body.Weight))) %>%
  mutate(IWat.norm = mean.iwat/1000/mean.weight*100,
         IWat.se = se.iwat/1000/mean.weight*100,
         Ewat.norm = mean.ewat/1000/mean.weight*100,
         Ewat.se = se.ewat/1000/mean.weight*100)
```

```{r statistics, results='asis'}
```

```{r iwat-normalized}
ymax <- with(fat.summary, max(Ewat.norm + Ewat.se))
plot <- with(fat.summary, barplot(cbind(IWat.norm,Ewat.norm), 
        beside=T, las=1, ylim=c(0,ymax), names.arg=c('IWAT','EWAT'), ylab="Percent of Body Weight"))

superpose.eb <- 
 function (x, y, ebl, ebu = ebl, length = 0.08, ...) 
 arrows(x, y + ebu, x, y - ebl, angle = 90, code = 3, 
 length = length, ...)

with(fat.summary, superpose.eb(plot,cbind(IWat.norm,Ewat.norm),cbind(IWat.se,Ewat.se)))
legend('topleft', levels(data$Treatment), bty='n', fill=grey.colors(2))
```


# Session Information

```{r sessionInfo}
sessionInfo()
```