---
title: "Age_Cushing_Overlap"
author: "Quynh Tran"
date: "April 12, 2015"
output: html_document
---

This is to find the overlap between the 2 gene lists: 1) genes that are differentially expressed by Cushing's after controlled for BMI and 2) genes that are differentially expressed by age (the data is downloaded from PMID: 23889843). This is to show that genes that found by our study are not effects of age, but the disease Cushing's itself.

```{r venn_Cushing_vs_Age, echo=FALSE, dev=c('pdf','png'), eval=FALSE}
cushings.gl <- read.csv("../data/processed/Annotated_Results_Cushings_bmi_adjusting.csv")
age.gl  <- read.table(file="../data/raw/gb-2013-14-7-r75-s3.txt", header=TRUE, sep="\t")

varsCushing <- "external_gene_id"
varsAge <- "HGNC_symbol"

cushing.sig <- cushings.gl[cushings.gl$padj_Cushing_vs_Con < 0.01 , varsCushing]

age.sig <- age.gl[age.gl$BH < 0.01, varsAge]
cushing.sig.unique <- unique(cushing.sig)
age.sig.unique <- unique(age.sig)

Lists <- list(cushing.sig.unique, age.sig.unique)

Lists <- lapply(Lists, function(x) as.character(unlist(x)))
items <- sort(unique(unlist(Lists)))   #put in alphabetical order
MAT <- matrix(rep(0, length(items)*length(Lists)), ncol=2)  #make a matrix of 0's
colnames(MAT) <- paste0("List", 1:2)
rownames(MAT) <- items
lapply(seq_along(Lists), function(i) {   #fill the matrix
    MAT[items %in% Lists[[i]], i] <<- table(Lists[[i]])
})

MAT   #look at the results

colnames(MAT) <- c("Cushings", "Age")
write.csv(MAT, file="../data/processed/Cushing_vs_Age_DEgenes.csv")
require(gplots)
venn(list(Cushing=cushing.sig.unique, Age=age.sig.unique))

library(venneuler)
v <- venneuler(MAT)
plot(v)

library(limma)
count <- vennCounts(MAT)
vennDiagram(count)

require(VennDiagram)
venn.diagram(list(cushing.sig.unique = 1:464, age.sig.unique = 454:638),fill = c("red", "green"),
  alpha = c(0.5, 0.5), cex = 2, cat.fontface = 4,lty =2, cat.cex=2, cat.dist=0.05, cat.pos=0.5,  filename = "./figures/vennCushing_Age.tiff");

```


#Session Info
```{r, echo=FALSE}
sessionInfo()
```

