Barplot Analysis of Cushing Results
=======================================

Used Analysed DESeq results.  There was no sequence data for sample 12128 and we removed the control patient id 29 due to his missing the exclusion criteria.

```{r file-input, echo=FALSE, warning=FALSE}
filename <- "RPKM_counts_Cushing_GRCh37.74.csv"
deseq.filename <- "Annotated_Results_Cushings_NotObese_and_Obese.csv"
#read in the file
normalized.data <- read.csv(filename, row.names='X')
deseq.data <- read.csv(deseq.filename, row.names='X')
sample_mapping <- read.csv("patient_sample_mapping.csv")
patient_info <- read.csv("patient_table.csv")
mapping <- merge(sample_mapping, patient_info, by.x="patient..", by.y="id")
mapping$samplename <- paste("sample", mapping$sample.., sep="")
mapping$group <- relevel(mapping$group, ref="non-functioning")
levels(mapping$group)[levels(mapping$group)=="non-functioning"] <- "Control"
levels(mapping$group)[levels(mapping$group)=="Cushing's"] <- "Cushing's"
levels(mapping$group)[levels(mapping$group)=="acromegaly"] <- "Acromegaly"
mapping$BMI.cat <- cut(mapping$BMI, breaks=c(0,30,50))
mapping$BMI.cat <- ifelse(mapping$BMI.cat=="(0,30]", "Not Obese", "Obese")

filtered.mapping <- mapping[mapping$patient.. != 29,]
filtered.normalized.data <- normalized.data[,colnames(normalized.data ) %in% filtered.mapping$samplename]
filtered.mapping.cush <- filtered.mapping[filtered.mapping$group!="Acromegaly",]
filtered.mapping.cush <- filtered.mapping.cush[order(filtered.mapping.cush$group),]
filtered.normalized.cush <- filtered.normalized.data[,colnames(filtered.normalized.data) %in% filtered.mapping.cush$samplename]
#colnames(filtered.normalized.cush) <- filtered.mapping.cush$group


#get gene names for transcripts
#library(biomaRt)
#ensembl = useMart("ensembl", dataset="hsapiens_gene_ensembl")
#gene.data <- getBM(attributes=c('ensembl_gene_id', 'hgnc_symbol'),filters = 'ensembl_gene_id', values = rownames(filtered.normalized.data), mart = ensembl)
annotation_output_file <- '../data/raw/Ensembl Gene Annotation.csv'
#write.csv(gene.data, annotation_output_file)
gene.data <- read.csv(annotation_output_file, row.names='X')
rpkm.data <- merge(filtered.normalized.cush, gene.data, by.x='row.names', by.y='ensembl_gene_id') 
rpkm.data.unique <- rpkm.data[!duplicated(rpkm.data$hgnc_symbol),]

rownames(rpkm.data.unique) <- rpkm.data.unique$hgnc_symbol
rpkm.data.unique <- rpkm.data.unique[,-1]

#paste gene here
genes.of.interest <- c("NR3C1","NR3C2","KLF5","CDKN2B","FASN","GYS1","GYS2","GBE1","HLA-DRB1","IDH1","LDHA","LDHB","PSMD8","SCD","FASN","STBD1")

#genes.of.interest.data <- rpkm.data.unique[genes.of.interest,]
#put the data in long format
library(reshape2)  
rpkm.long <- reshape(rpkm.data.unique, direction="long", varying=list(names(rpkm.data.unique)[1:16]), v.names="Expression", idvar="hgnc_symbol", timevar="Disease", ids=rownames(rpkm.data.unique), times=c(rep('Control',11),rep("Cushing's",5)))
rpkm.bmi <- reshape(rpkm.data.unique, direction="long", varying=list(names(rpkm.data.unique)[1:16]), v.names="Expression", idvar="hgnc_symbol", ids=rownames(rpkm.data.unique), timevar="BMI",  times=filtered.mapping.cush$BMI.cat[1:16])
rpkm.long$BMI <- rpkm.bmi$BMI

#calculate standard error
library(plyr)
rpkm.long.cal <- ddply(rpkm.long, .(hgnc_symbol,Disease,BMI), summarise, se = sd(Expression, na.rm=T)/sqrt(length(Expression)), mean_Expression = mean(Expression, na.rm=T))

rpkm.long.cal$Disease <- factor(rpkm.long.cal$Disease)
rpkm.long.cal$BMI <- factor(rpkm.long.cal$BMI)

goi.long.cal <- rpkm.long.cal[rpkm.long.cal$hgnc_symbol%in%genes.of.interest,]
colnames(goi.long.cal)[1] <- "Genes"
goi.long.cal <- goi.long.cal[goi.long.cal$Genes!='NA',]
goi.long.cal <- goi.long.cal[goi.long.cal$Genes!='NA.1',]
goi.long.cal <- goi.long.cal[order(rev(goi.long.cal$Genes), goi.long.cal$Disease, decreasing=T),]

rpkm.long.cal <- rpkm.long.cal[order(rev(rpkm.long.cal$hgnc_symbol), rpkm.long.cal$Disease, decreasing=T),]
```

```{r barplots, dev=c('png','pdf'), echo=FALSE, fig.show='asis', warning=FALSE}
library(reshape2)
library(ggplot2)
for (gene in genes.of.interest) {
  #pdf(sprintf('../figures/%s-barplot.pdf', gene))
  gene.data <- goi.long.cal[goi.long.cal$Genes==gene,]
  #pdf(paste('../figures/',gene,'-barplot.pdf',sep=""))
  ggplot(gene.data, aes(x=BMI,y=mean_Expression, fill=Disease)) + 
    geom_bar(stat="identity", position="dodge") + 
    geom_errorbar(aes(ymin=mean_Expression-se, ymax=mean_Expression+se), position=position_dodge(0.9),width=.2) + xlab("") + ylab("mRNA Expression (RPKM)")+ theme_bw() + ggtitle(gene) + theme(panel.grid.minor = element_blank()) + theme(panel.grid.major = element_blank()) + theme(panel.border=element_blank()) + scale_x_discrete(labels=gene.data$BMI) + theme(axis.line = element_line(color = 'black'))+scale_colour_grey(start = 0.5, end = .9)
  ggsave(filename=paste('../Figures/Cushing_BMI/Cushing-BMI-',gene,'-barplot.pdf',sep=""))
}

```

```{r cushing-lipase-barplots, dev=c('png','pdf'), echo=FALSE, fig.show='asis',  warning=FALSE}
#missing lipb, fix showing cush/control
lipases <- c("LPL","PNPLA2", "MGLL","LIPE", "LIPA", "LIPC", "PNLIP","LIPG","CEL","LIPF","LIPH", "DAGLB","DAGLA", "LIPI","LIPN","LIPM","LIPK","LIPJ")

#lipase.data <- getBM(attributes=c('ensembl_gene_id', 'hgnc_symbol'),
 #                  filters = 'hgnc_symbol', values = lipases, mart = ensembl)
lipase.cal <- rpkm.long.cal[rpkm.long.cal$hgnc_symbol%in%lipases,]
colnames(lipase.cal)[1] <- "Genes"

nonObese.sig.genes <- subset(deseq.data, padj_NotObese_CushingvCon<0.05)$external_gene_id
nonObese.sig.genes <- as.character(nonObese.sig.genes)
obese.sig.genes <- subset(deseq.data, padj_Obese_CushingvCon<0.05)$external_gene_id
obese.sig.genes <- as.character(obese.sig.genes)

#qplot(data=lipase.cal, x=Genes, y=mean_Expression, geom="bar", fill=Disease, position="dodge", stat="identity")
library(ggplot2)
ggplot(lipase.cal, aes(x=Genes, y=mean_Expression, fill=Disease))+
    geom_bar(stat="identity",width=.8, position=position_dodge(width=.8), col="black", show_guide=F) +
    geom_errorbar(position=position_dodge(width=.8), aes(ymin=mean_Expression-se, ymax=mean_Expression+se), width=.2)+
    facet_grid(BMI~.)+
    theme_bw()+theme(axis.text.x=element_text(angle=90))+xlab("")+ ylab("mRNA Expression (RPKM)") +
    theme(panel.grid.minor = element_blank()) + theme(panel.grid.major = element_blank()) + 
    theme(panel.border=element_blank())+ 
    theme(axis.line = element_line(color = 'black')) +
    scale_fill_grey(start = 0.3, end = .9) +
    #guides(fill = guide_legend(keywidth = .5, keyheight = .5)) +
    theme(text = element_text(size=20), axis.text.x = element_text(angle=70,hjust=.5,vjust=.5)) +
    theme(legend.position=c(.60,.90))

ggsave("../Figures/Cushing_BMI/Cushing-BMI-all-lipases-RPKM.pdf")

```

```{r draw lipase genes, echo=FALSE, fig.show='asis',  warning=FALSE}
#draw each lipase gene
gene="LPL"
for (gene in lipases) {
  #pdf(sprintf('../figures/Cushing-%s-barplot.pdf', gene))
  gene.data <- lipase.cal[lipase.cal$Genes==gene,]
  #pdf(paste('../figures/Cushing-',gene,'-barplot.pdf',sep=""))
  ggplot(gene.data, aes(x=BMI,y=mean_Expression, fill=Disease)) + 
    geom_bar(stat="identity", position="dodge", col="black") + 
    geom_errorbar(aes(ymin=mean_Expression-se, ymax=mean_Expression+se), position=position_dodge(0.9), width=.2) + 
    scale_x_discrete(labels=gene.data$BMI) + 
    xlab("") + ylab("RPKM")+ theme_bw() + ggtitle(gene) + 
    theme(panel.grid.minor = element_blank()) + 
    theme(panel.grid.major = element_blank()) + 
    theme(panel.border=element_blank()) + 
    theme(axis.line = element_line(color = 'black'))
  
  ggsave(filename=paste('../Figures/Cushing_BMI/Cushing-BMI-lipase-',gene,'-barplot.pdf',sep=""))
}
#draw each gene in the obese.sig.genes list
for (gene in obese.sig.genes) {
  #pdf(sprintf('../figures/Cushing-%s-barplot.pdf', gene))
  gene.data <- rpkm.long.cal[rpkm.long.cal$hgnc_symbol==gene,]
  #pdf(paste('../figures/Cushing-',gene,'-barplot.pdf',sep=""))
  ggplot(gene.data, aes(x=BMI,y=mean_Expression, fill=Disease)) + 
    geom_bar(stat="identity", position="dodge", col="black") + 
    geom_errorbar(aes(ymin=mean_Expression-se, ymax=mean_Expression+se), position=position_dodge(0.9), width=.2) + 
    scale_x_discrete(labels=gene.data$BMI) + 
    xlab("") + ylab("RPKM")+ theme_bw() + ggtitle(gene) + 
    theme(panel.grid.minor = element_blank()) + 
    theme(panel.grid.major = element_blank()) + 
    theme(panel.border=element_blank()) + 
    theme(axis.line = element_line(color = 'black'))
  
  ggsave(filename=paste('../Figures/Cushing_BMI/Cushing-Obese-',gene,'-barplot.pdf',sep=""))
}
```

```{r grouped-plots, echo=FALSE, fig.show='asis' }
insulin <- c("FASN", "TCF7L2", "SOCS2", "AKT1", "PYGM", "ACACA", "SLC2A4")
unsat_FA <- c("ELOVL5", "ELOVL6", "FADS1", "FADS2", "SCD", "HSD17B12", "ACOX1", "HADHA", "PECR")
lipolysis <- c("LPL", "ABHD5", "ADRB3", "ACVR1C", "PNPLA", "LIPE", "MGLL", "PNPLA2")

cortisol_signaling <-  c("HSD11B1","HSD11B2","NR3C1","NR3C2")
igf_complex <- c("IGF1","IGFBP3", "IGFBP5", "IGFALS")
ags_isoforms <- c("GPSM1","GPSM2","GPSM3")
rgs_isoforms <- paste("RGS", seq(1,22), sep="")
lipid_metabolism <- c('FADS1','FADS2','DHCR24','TFCP2L1','PNPLA3','DGAT2','DHCR7','PCYT2','CYP7B1','HPGD','PLCE1','IDI1','NPC1L1','PDSS2','AGPAT2')
tg_synthesis <- c('ELOVL6','FASN','GPAM','DGAT2','ACACA','ACSL1','ELOVL5','ACLY','HSD17B12','ACSL4','AGPAT2','SLC25A1','GPD1','ELOVL1','ACSL3','LPIN1','AGPAT3','GK')
carb_metabolism <- c('ALDOC','GYS2','ME1','SLC2A5','CHST4','IDH1','CHST11','HPSE','SLC25A10','ACLY','PGD','FBP1','ACO1','NNT','XYLT1','ALDOA','CHST8','UGP2','TALDO1','ST3GAL5','GYG2','GFPT1','PDHB','NANP','NEU3','GNS','FUT8','PDK3','FH','PYGB','CHIT1','CSGALNACT2','EPM2A','ACN9','ACO2','GALNT7','CHST2','MPDU1','SDHC')
tca_citric_acid <- c('IDH2','NNT','SUCLG1','OGDH','DLD','FH','CS','ACO2','SDHC','SUCLA2','SDHB','IDH3A')
bcaa_degradation <- c('AOX1','BCAT1','IL4I1','ACAT2','OXCT1','HMGCS1','ALDH9A1','MCCC1','ACAA2','EHHADH','DLD','ECHS1','ALDH3A2','HIBCH','DBT','ACADSB','ACADM','BCKDHB','IVD','HADHA','PCCB')
interferon_signaling <- c('EIF4A3','SOCS1','GBP1','HLA-DRB1','IFI35','UBE2L6','IFNAR2','UBA52','HLA-A','MX1','PTPN6','B2M','RPS27A','TYK2','NUP85','PML','HLA-DQA1','IP6K2','IFIT1','EIF4A2','MX2','NUP35','TRIM25','AAAS','GBP7','IRF6','FLNB','PLCG1','GBP5','IFI27','HERC5','PSMB8','HLA-B','XAF1','ISG15','OASL','IRF1','HLA-F','NCAM1','IFITM3','UBA7','IRF3','IFITM2','HLA-DPB1','IRF4','IFITM1','IRF7','IRF9','HLA-DPA1','HLA-C')
intferon_gamma <- c('SOCS1','GBP1','HLA-DRB1','HLA-A','PTPN6','B2M','PML','HLA-DQA1','GBP7','IRF6','GBP5','HLA-B','OASL','IRF1','HLA-F','NCAM1','IRF3','HLA-DPB1','IRF4','IRF7','IRF9','HLA-DPA1','HLA-C')
interferon_gamma_no_b2m <- c('SOCS1','GBP1','HLA-DRB1','HLA-A','PTPN6','PML','HLA-DQA1','GBP7','IRF6','GBP5','HLA-B','OASL','IRF1','HLA-F','NCAM1','IRF3','HLA-DPB1','IRF4','IRF7','IRF9','HLA-DPA1','HLA-C')
IRF_isoforms <- c('IRF1','IRF2','IRF3','IRF4','IRF5','IRF6','IRF7','IRF8','IRF9')
activin <- c('ACVR1','ACVR1B','ACVR1C','ACVR2A','ACVR2B','ACVRL1','INHBA','INHBB','GREM1')
M_PHASE_OF_MITOTIC_CELL_CYCLE <- c('ANLN','CDKN2B','BUB1','ESPL1','BUB1B','TPX2','KIF11','AURKA','ZWINT','NCAPH','TTK','NUSAP1','MAD2L1','KIF2C','UBE2C','CDCA5','KIF15','BIRC5','CENPE','DLGAP5','NDC80','SMC4','PKMYT1','MPHOSPH9','RCC1','MPHOSPH6','EGF','PLK1','NEK6')
STEROID_BIOSYNTHETIC_PROCESS <- c('DHCR24','TFCP2L1','DHCR7','CYP7B1','NPC1L1','CYP19A1','NR0B1')
REACTOME_TRIGLYCERIDE_BIOSYNTHESIS <- c('ELOVL6','FASN','GPAM','DGAT2','ACACA','ACSL1','ELOVL5','ACLY','HSD17B12','ACSL4','AGPAT2','SLC25A1','GPD1','ELOVL1','ACSL3','LPIN1','AGPAT3','GK')
KEGG_BIOSYNTHESIS_OF_UNSATURATED_FATTY_ACIDS <- c('SCD','FADS1','FADS2','ELOVL6','ELOVL5','HSD17B12','PECR','PTPLB','ACOX1')
PROTEASOME_COMPLEX <- c('PSMD14','PSMD1','PSMD8','PSMC2','PSMD12','PSMD2','KIAA0368','PSMD11','PSMD7','PSMD3','PSMC4','PSMC6','ADRM1','PSMD10','PSMC5','PSME3','PSMC3','PSMD13','PSMD5')
KEGG_VALINE_LEUCINE_AND_ISOLEUCINE_DEGRADATION <- c('AOX1','BCAT1','IL4I1','ACAT2','OXCT1','HMGCS1','ALDH9A1','MCCC1','ACAA2','EHHADH','DLD','ECHS1','ALDH3A2','HIBCH','DBT','ACADSB','ACADM','BCKDHB','IVD','HADHA','PCCB')
KEGG_RIBOSOME <- c('RPS7','RPL7','RPL10L','RPL31','RPL6','RPL3L','RPL3','RPL22','RPS4X','RPL36AL','RPL11','RPL23','RPS5','RPL27','RPL37A','RPL28','RPS13','RPS24','RPL15','RPL39','RPLP1','RPS8','RPS3','RPL32','UBA52','RPL35A','RPL35','RPL10A','RPL26L1','RSL24D1','RPS6','RPS3A','RPL18A','RPS27A','RPS15','RPL13A','RPL19','RPL38','RPL30','RPL17','RPL24','RPL27A','RPL21','RPS11','RPS19','RPS29','RPS16','RPL13','RPL34','RPS15A','RPS25','RPL23A','RPL26','RPL36','RPL41','RPL12','RPL8','RPS18','RPS28','RPL37','RPS9','FAU','RPS26','RPL18','RPS21','RPS27')
KEGG_CITRATE_CYCLE_TCA_CYCLE <- c('IDH1','DLAT','IDH2','ACLY','ACO1','MDH1','PC','SUCLG1','OGDH','PDHB','DLD','FH','CS','ACO2','SDHC','PDHA1','SUCLA2')
KEGG_PYRUVATE_METABOLISM <- c('ME1','ACACA','LDHB','LDHA','DLAT','ACSS2','ACAT2','ALDH9A1','MDH1','PC','ACYP2','ACACB','PDHB','ME2','DLD','ALDH3A2')
KEGG_STARCH_AND_SUCROSE_METABOLISM <- c('GYS2','GBE1','HK3','GYS1','UGT2B4','ENPP1','UGP2','PGM1','PYGL','PGM2L1','PYGB','AGL')
KEGG_ALLOGRAFT_REJECTION <- c('HLA-DRB1','HLA-DMB','HLA-A','CD40','CD28','FASLG','HLA-DQA1','CD40LG','HLA-DQB1','PRF1','HLA-B','HLA-F','HLA-E','HLA-DOA','HLA-DPB1','HLA-DRA','HLA-DPA1','HLA-C')
KEGG_BASAL_CELL_CARCINOMA <- c('WNT10A','LEF1','TP53','AXIN2','FZD10','WNT5A','FZD2','WNT9B','AXIN1','FZD3','FZD8','DVL2','PTCH2','WNT2','SMO','WNT3','APC2','WNT10B','WNT11','BMP4','WNT5B','WNT9A','WNT4')
M_PHASE_OF_MITOTIC_CELL_CYCLE_no_CDKN2B <- c('ANLN','BUB1','ESPL1','BUB1B','TPX2','KIF11','AURKA','ZWINT','NCAPH','TTK','NUSAP1','MAD2L1','KIF2C','UBE2C','CDCA5','KIF15','BIRC5','CENPE','DLGAP5','NDC80','SMC4','PKMYT1','MPHOSPH9','RCC1','MPHOSPH6','EGF','PLK1','NEK6')
MITOCHONDRIONsub <- c('MTCH1','TIMM10','COQ6','MRPL23','TSFM','UQCRC1','ATP5O','COX11')

CALMODULIN_BINDING <- c('NRGN','RGS16','RGS2','RGS1','SPHK1','TRPV4','DAPK1','TTN','MYO9B','MYO7A','RIT1','MARCKS','MYO3A','ATPIF1')

KEGG_LYSOSOME <- c('ACP5','LAPTM5','SLC11A1','LIPA','CTSH','CTSS','LAMP3','CTSC','CTSG','DNASE2B','TCIRG1','CTSD','ATP6V0D2','GM2A','MANBA','NAPSA','HYAL1','NPC2','CTSF','CLN3','CTSZ','ATP6V0B','GAA','PPT1','LGMN','CTSB','TPP1','GUSB','AP1S2','NAGA','HEXB','SLC11A2','NEU1','ARSB','FUCA1','MAN2B1','M6PR','GGA1','IDS','LAPTM4B','CTSK','ATP6V0A1','CTNS','IGF2R','GGA2','MCOLN1','AP4B1','AP1S3','GALC','AP1S1','ATP6AP1','AP4S1','LAMP1','GNPTAB','GGA3','LAMP2','GBA','HEXA','GNPTG','PSAP','ARSA','SLC17A5','GALNS','AP1B1','NAGPA','ATP6V1H')
KEGG_LYSOSOME_high <- c('CTSB','CTSD','CTSZ','CTSK','CTSS','LAPTM4A','LAPTM4B','LAPTM5','LAMP1','LAMP2','NPC1','NPC2','LGMN','LIPA','M6PR','TPP1','PPT1')
ATP_SYNTHASE <- c('ATP6V1A','ATP6V1B2','ATP6V1B2','ATP6V1C1','ATP6V1C2','ATP6V1D','ATP6V1E1','ATP6V1E2','ATP6V1F','ATP6V1G1','ATP6V1G2','ATP6V1G3','ATP6V1H')

gene.data.name <- c('igf_complex','rgs_isoforms','ags_isoforms', 'lipid_metabolism', 'tg_synthesis','carb_metabolism','cortisol_signaling','tca_citric_acid', 'bcaa_degradation','interferon_signaling','intferon_gamma','interferon_gamma_no_b2m','IRF_isoforms','activin','M_PHASE_OF_MITOTIC_CELL_CYCLE','STEROID_BIOSYNTHETIC_PROCESS','REACTOME_TRIGLYCERIDE_BIOSYNTHESIS','KEGG_BIOSYNTHESIS_OF_UNSATURATED_FATTY_ACIDS','PROTEASOME_COMPLEX','KEGG_VALINE_LEUCINE_AND_ISOLEUCINE_DEGRADATION','KEGG_RIBOSOME','KEGG_CITRATE_CYCLE_TCA_CYCLE','KEGG_PYRUVATE_METABOLISM','KEGG_STARCH_AND_SUCROSE_METABOLISM','KEGG_ALLOGRAFT_REJECTION','KEGG_BASAL_CELL_CARCINOMA','M_PHASE_OF_MITOTIC_CELL_CYCLE_no_CDKN2B','MITOCHONDRIONsub','CALMODULIN_BINDING','KEGG_LYSOSOME','KEGG_LYSOSOME_high','ATP_SYNTHASE')
for (name in gene.data.name){
  #name <- as.name(name) #convert string to variable name
  gene.data <- rpkm.long.cal[rpkm.long.cal$hgnc_symbol%in%eval(as.name(name)),]
  gene.data$hgnc_symbol <- factor(gene.data$hgnc_symbol, levels=eval(as.name(name)))
  
  ggplot(gene.data, aes(x=hgnc_symbol, y=mean_Expression, fill=Disease))+ 
    #this line together with show_guide=F and the element_rect=black get rid of the slash in legend box
    geom_bar(stat="identity", width=.8, position=position_dodge(width=.8)) +
    geom_bar(stat="identity",width=.8, position=position_dodge(width=.8), col="black", show_guide=F) +
    geom_errorbar(position=position_dodge(width=.8), aes(ymin=mean_Expression-se, ymax=mean_Expression+se), width=.2)+
    facet_grid(BMI~.)+
    theme_bw()+theme(axis.text.x=element_text(angle=90))+xlab("")+ ylab("mRNA Expression (RPKM)") +
    theme(panel.grid.minor = element_blank()) + theme(panel.grid.major = element_blank()) + 
    theme(panel.border=element_blank())+ 
    theme(axis.line = element_line(color = 'black')) +
    scale_fill_grey(start = 0.3, end = .9, guide=guide_legend()) +
    #guides(fill = guide_legend(keywidth = .5, keyheight = .5)) +
    theme(text = element_text(size=20), axis.text.x = element_text(angle=70,hjust=.3,vjust=.3)) +
    theme(legend.position=c(.60,.90), legend.title=element_blank(), legend.key=element_rect(color="black"))   + ggtitle(name)
    
  ggsave(filename=paste('../Figures/Cushing_BMI/Cushing-BMI-', name, '-barplot.pdf',sep=""))
}

```


The data used is in the file **`r filename`**.  This file was most recently processed on ```r date()```.


Session Information
---------------------

```{r session-information}
sessionInfo()
```
